[DefaultOutputDestinationSettings = [DestinationDefinition = [Kind = "Reference", QueryName = "DefaultDestination", IsNewTarget = true], UpdateMethod = [Kind = "Replace"], DestinationTypeSettings = [Kind = "Table"]], StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[BindToDefaultDestination = true]
shared procore_payment_application_line_items_silver = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "1f7caed6-f88a-4e52-bc83-9a498a165301"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "4256b1ed-3884-4e26-96b5-aac4d8e6281f"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "procore_payment_application_line_items_raw", ItemKind = "Table"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 2", {"billing_date"}),
  #"Changed column type" = Table.TransformColumnTypes(#"Removed columns", {{"period_start", type date}, {"period_end", type date}, {"total_amount_accrued_this_period", Currency.Type}, {"scheduled_value", Currency.Type}, {"work_completed_from_previous_application", Currency.Type}, {"work_completed_this_period", Currency.Type}, {"total_completed_and_stored_to_date", Currency.Type}, {"balance_to_finish", Currency.Type}, {"total_retainage_currently_retained", Currency.Type}, {"work_completed_retainage_retained_this_period", Currency.Type}, {"work_completed_retainage_released_this_period", Currency.Type}, {"materials_presently_stored", Currency.Type}, {"total_completed_and_stored_to_date_percent", type number}}),
  #"Added custom" = Table.AddColumn(#"Changed column type", "Custom", each [total_completed_and_stored_to_date_percent] / 100),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Added custom", {{"Custom", Percentage.Type}}),
  #"Reordered columns" = Table.ReorderColumns(#"Changed column type 1", {"payment_application_id", "payment_application_number", "payment_application_status", "invoice_number", "period_start", "period_end", "total_amount_accrued_this_period", "prime_contract_id", "project_id", "project_name", "line_item_id", "item_number", "cost_code_id", "cost_code_full_code", "cost_code_name", "wbs_flat_code", "wbs_description", "description_of_work", "scheduled_value", "work_completed_from_previous_application", "work_completed_this_period", "total_completed_and_stored_to_date", "Custom", "total_completed_and_stored_to_date_percent", "materials_presently_stored", "balance_to_finish", "total_retainage_currently_retained", "work_completed_retainage_retained_this_period", "work_completed_retainage_released_this_period"}),
  #"Removed columns 1" = Table.RemoveColumns(#"Reordered columns", {"total_completed_and_stored_to_date_percent"}),
  #"Renamed columns" = Table.RenameColumns(#"Removed columns 1", {{"Custom", "total_completed_and_stored_to_date_percent"}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Renamed columns", {{"cost_code_id", Int64.Type}}),
  #"Reordered columns 1" = Table.ReorderColumns(#"Changed column type 2", {"project_id", "payment_application_id", "payment_application_number", "payment_application_status", "invoice_number", "period_start", "period_end", "total_amount_accrued_this_period", "prime_contract_id", "project_name", "line_item_id", "item_number", "cost_code_id", "cost_code_full_code", "cost_code_name", "wbs_flat_code", "wbs_description", "description_of_work", "scheduled_value", "work_completed_from_previous_application", "work_completed_this_period", "total_completed_and_stored_to_date", "total_completed_and_stored_to_date_percent", "materials_presently_stored", "balance_to_finish", "total_retainage_currently_retained", "work_completed_retainage_retained_this_period", "work_completed_retainage_released_this_period"}),
  #"Renamed columns 1" = Table.RenameColumns(#"Reordered columns 1", {{"project_id", "Project ID"}}),
  #"Reordered columns 2" = Table.ReorderColumns(#"Renamed columns 1", {"Project ID", "line_item_id", "payment_application_id", "payment_application_number", "payment_application_status", "invoice_number", "period_start", "period_end", "total_amount_accrued_this_period", "prime_contract_id", "project_name", "item_number", "cost_code_id", "cost_code_full_code", "cost_code_name", "wbs_flat_code", "wbs_description", "description_of_work", "scheduled_value", "work_completed_from_previous_application", "work_completed_this_period", "total_completed_and_stored_to_date", "total_completed_and_stored_to_date_percent", "materials_presently_stored", "balance_to_finish", "total_retainage_currently_retained", "work_completed_retainage_retained_this_period", "work_completed_retainage_released_this_period"}),
  #"Renamed columns 2" = Table.RenameColumns(#"Reordered columns 2", {{"line_item_id", "Line Item ID"}}),
  #"Reordered columns 3" = Table.ReorderColumns(#"Renamed columns 2", {"Project ID", "Line Item ID", "total_amount_accrued_this_period", "payment_application_id", "payment_application_number", "payment_application_status", "invoice_number", "period_start", "period_end", "prime_contract_id", "project_name", "item_number", "cost_code_id", "cost_code_full_code", "cost_code_name", "wbs_flat_code", "wbs_description", "description_of_work", "scheduled_value", "work_completed_from_previous_application", "work_completed_this_period", "total_completed_and_stored_to_date", "total_completed_and_stored_to_date_percent", "materials_presently_stored", "balance_to_finish", "total_retainage_currently_retained", "work_completed_retainage_retained_this_period", "work_completed_retainage_released_this_period"}),
  #"Removed columns 2" = Table.RemoveColumns(#"Reordered columns 3", {"project_name"}),
  #"Renamed columns 3" = Table.RenameColumns(#"Removed columns 2", {{"prime_contract_id", "Prime Contract ID"}}),
  #"Reordered columns 4" = Table.ReorderColumns(#"Renamed columns 3", {"Project ID", "Line Item ID", "Prime Contract ID", "cost_code_id", "total_amount_accrued_this_period", "payment_application_id", "payment_application_number", "payment_application_status", "invoice_number", "period_start", "period_end", "item_number", "cost_code_full_code", "cost_code_name", "wbs_flat_code", "wbs_description", "description_of_work", "scheduled_value", "work_completed_from_previous_application", "work_completed_this_period", "total_completed_and_stored_to_date", "total_completed_and_stored_to_date_percent", "materials_presently_stored", "balance_to_finish", "total_retainage_currently_retained", "work_completed_retainage_retained_this_period", "work_completed_retainage_released_this_period"}),
  #"Renamed columns 4" = Table.RenameColumns(#"Reordered columns 4", {{"cost_code_id", "Cost Code ID"}}),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Renamed columns 4", {{"Project ID", type text}, {"Line Item ID", type text}, {"Prime Contract ID", type text}, {"Cost Code ID", type text}, {"payment_application_id", type text}, {"payment_application_number", type text}}),
  #"Replaced value" = Table.ReplaceValue(#"Changed column type 3", "", "0", Replacer.ReplaceValue, {"Cost Code ID"}),
  #"Replaced value 1" = Table.ReplaceValue(#"Replaced value", null, "0", Replacer.ReplaceValue, {"Cost Code ID"}),
  #"Removed columns 3" = Table.RemoveColumns(#"Replaced value 1", {"item_number", "cost_code_full_code", "cost_code_name", "wbs_flat_code", "wbs_description", "description_of_work"}),
  #"Renamed columns 5" = Table.RenameColumns(#"Removed columns 3", {{"work_completed_this_period", "Work Completed This Period"}}),
  #"Added custom 1" = Table.AddColumn(#"Renamed columns 5", "Billing Period", each Date.Month([period_start])),
  #"Changed column type 4" = Table.TransformColumnTypes(#"Added custom 1", {{"Billing Period", type number}}),
  #"Reordered columns 5" = Table.ReorderColumns(#"Changed column type 4", {"Project ID", "Line Item ID", "Prime Contract ID", "Cost Code ID", "total_amount_accrued_this_period", "payment_application_id", "payment_application_number", "payment_application_status", "invoice_number", "Billing Period", "period_start", "period_end", "scheduled_value", "work_completed_from_previous_application", "Work Completed This Period", "total_completed_and_stored_to_date", "total_completed_and_stored_to_date_percent", "materials_presently_stored", "balance_to_finish", "total_retainage_currently_retained", "work_completed_retainage_retained_this_period", "work_completed_retainage_released_this_period"}),
  #"Removed columns 4" = Table.RemoveColumns(#"Reordered columns 5", {"period_end", "period_start"})
in
  #"Removed columns 4";
shared DefaultDestination = Lakehouse.Contents([EnableFolding = false]){[workspaceId = "1f7caed6-f88a-4e52-bc83-9a498a165301"]}[Data]{[lakehouseId = "2e05dca7-ff80-4646-b711-6681dd4993e1"]}[Data];
