# Provision the manual-input lists for the Monthly Progress Report.
#
# GENERATED by _local/make_sharepoint.py from sql/gold/40_man_tables.sql.
# Do not edit by hand - the column names must stay identical to the man_* tables,
# and CD_Manual_Ingest maps them 1:1 with no translation layer.
#
# ---------------------------------------------------------------------------
# HOW TO RUN THIS  (about five minutes, once)
#
# 0. The SITE must already exist. Create it in SharePoint first if it does not:
#    SharePoint -> Create site -> Team site -> name it 'Affect Project Reporting'.
#    Note its URL; that is the -Url below.
#
# 1. Install the module:
#
#        Install-Module PnP.PowerShell -Scope CurrentUser -Force
#
# 2. Register an Entra app for sign-in. PnP.PowerShell 2.x REMOVED the built-in
#    multi-tenant app, so `Connect-PnPOnline -Interactive` on its own now fails
#    with 'ClientId is required'. This is the step people get stuck on. Run it
#    ONCE per tenant - it prints a ClientId, keep that:
#
#        Register-PnPEntraIDAppForInteractiveLogin -ApplicationName 'PnP Rocks' -Tenant <tenant>.onmicrosoft.com -Interactive
#
#    It asks a tenant admin to consent. If you are not one, someone who is has to
#    approve it - that is the only admin step in this whole file.
#
# 3. Connect and run. Run it from THIS folder, so it finds cd-projects.csv:
#
#        Connect-PnPOnline -Url https://<tenant>.sharepoint.com/sites/<site> -Interactive -ClientId <the id from step 2>
#        ./provision-sharepoint.ps1
#
#    (Commands are on one line each on purpose - a copied backslash is not a
#    PowerShell line continuation and fails with a confusing parse error.)
#
# 4. Nothing. CD Projects populates itself from cd-projects.csv, and the nine
#    lists are ready to type into. Point CD_Manual_Ingest at the site when you
#    want the rows flowing through to the report.
# ---------------------------------------------------------------------------
#
# Idempotent: an existing list is left alone and its missing columns are added, so
# re-running after a schema change is safe and is the intended way to apply one.

$ErrorActionPreference = 'Stop'

if (-not (Get-PnPContext)) { throw 'Connect-PnPOnline first.' }

function Ensure-List($title) {
    $existing = Get-PnPList -Identity $title -ErrorAction SilentlyContinue
    if ($null -eq $existing) {
        Write-Host "creating $title"
        $existing = New-PnPList -Title $title -Template GenericList -EnableVersioning
    } else {
        Write-Host "$title exists - adding any missing columns"
    }
    # Versioning is what gives every field change a who and a when. The spreadsheet
    # has never had that: a risk rating can change today with no record that it did.
    Set-PnPList -Identity $title -EnableVersioning $true -MajorVersions 500
    return $existing
}

# ---------------------------------------------------------------- lookup source
# Built FIRST because every other list points at it. A free-text project name is
# how '1100 Fulton' and '1100 Fulton St' become two projects in a report that then
# under-counts both. A lookup column cannot be misspelled.
$projectsList = Ensure-List "CD Projects"
Add-PnPField -List "CD Projects" -DisplayName "ProjectName" -InternalName "ProjectName" -Type Text -AddToDefaultView -ErrorAction SilentlyContinue | Out-Null
Add-PnPField -List "CD Projects" -DisplayName "IsActive" -InternalName "IsActive" -Type Boolean -AddToDefaultView -ErrorAction SilentlyContinue | Out-Null

# Title holds the Procore project id, e.g. 562949955001573.
#
# Populated from cd-projects.csv sitting next to this script, exported from
# dim_Project. Typing 19 project ids by hand is 19 chances to transpose a digit,
# and a wrong id here does not error - it creates a lookup entry that no fact row
# ever joins to, so the project silently reports zeros.
$csv = Join-Path $PSScriptRoot 'cd-projects.csv'
if (Test-Path $csv) {
    $existing = (Get-PnPListItem -List "CD Projects" -PageSize 500).FieldValues.Title
    foreach ($row in Import-Csv $csv) {
        if ($existing -contains $row.ProjectKey) { continue }
        Add-PnPListItem -List "CD Projects" -Values @{
            Title = $row.ProjectKey; ProjectName = $row.ProjectName
            IsActive = ($row.IsActive -eq 'TRUE')
        } | Out-Null
        Write-Host "  + $($row.ProjectName)"
    }
} else {
    Write-Host "cd-projects.csv not found - populate CD Projects by hand"
}

# --------------------------------------------------------------------------
# CD Wins  ->  man_Wins
$list = Ensure-List "CD Wins"
try {
    Add-PnPField -List $list -DisplayName "ProjectKey" -InternalName "ProjectKey" -Type Lookup -AddToDefaultView -ErrorAction Stop | Out-Null
    Set-PnPField -List $list -Identity "ProjectKey" -Values @{ LookupList = $projectsList.Id.ToString(); LookupField = "Title"; Required = $true }
    Add-PnPField -List $list -DisplayName "MonthStart" -InternalName "MonthStart" -Type DateTime -AddToDefaultView | Out-Null
    Set-PnPField -List $list -Identity "MonthStart" -Values @{ Required = $true; Description = "Always the FIRST of the reporting month, e.g. 2026-08-01." }
    Add-PnPField -List $list -DisplayName "WinNumber" -InternalName "WinNumber" -Type Number -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "Description" -InternalName "Description" -Type Note -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "WinType" -InternalName "WinType" -Type Text -AddToDefaultView | Out-Null
} catch [System.Management.Automation.RuntimeException] {
    # Add-PnPField throws if the column already exists. That is the idempotent
    # path, not a failure - anything else rethrows.
    if ($_.Exception.Message -notmatch 'already exists') { throw }
}

# --------------------------------------------------------------------------
# CD Risks  ->  man_Risks
$list = Ensure-List "CD Risks"
try {
    Add-PnPField -List $list -DisplayName "ProjectKey" -InternalName "ProjectKey" -Type Lookup -AddToDefaultView -ErrorAction Stop | Out-Null
    Set-PnPField -List $list -Identity "ProjectKey" -Values @{ LookupList = $projectsList.Id.ToString(); LookupField = "Title"; Required = $true }
    Add-PnPField -List $list -DisplayName "MonthStart" -InternalName "MonthStart" -Type DateTime -AddToDefaultView | Out-Null
    Set-PnPField -List $list -Identity "MonthStart" -Values @{ Required = $true; Description = "Always the FIRST of the reporting month, e.g. 2026-08-01." }
    Add-PnPField -List $list -DisplayName "RiskNumber" -InternalName "RiskNumber" -Type Number -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "Description" -InternalName "Description" -Type Note -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "ImpactCode" -InternalName "ImpactCode" -Type Choice -Choices "HIGH","MEDIUM","LOW" -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "Mitigation" -InternalName "Mitigation" -Type Note -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "OwnerRole" -InternalName "OwnerRole" -Type Text -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "StatusCode" -InternalName "StatusCode" -Type Choice -Choices "NOT_STARTED","PLANNED","IN_PROGRESS","COMPLETE" -AddToDefaultView | Out-Null
} catch [System.Management.Automation.RuntimeException] {
    # Add-PnPField throws if the column already exists. That is the idempotent
    # path, not a failure - anything else rethrows.
    if ($_.Exception.Message -notmatch 'already exists') { throw }
}

# --------------------------------------------------------------------------
# CD PriorityItems  ->  man_PriorityItems
$list = Ensure-List "CD PriorityItems"
try {
    Add-PnPField -List $list -DisplayName "ProjectKey" -InternalName "ProjectKey" -Type Lookup -AddToDefaultView -ErrorAction Stop | Out-Null
    Set-PnPField -List $list -Identity "ProjectKey" -Values @{ LookupList = $projectsList.Id.ToString(); LookupField = "Title"; Required = $true }
    Add-PnPField -List $list -DisplayName "MonthStart" -InternalName "MonthStart" -Type DateTime -AddToDefaultView | Out-Null
    Set-PnPField -List $list -Identity "MonthStart" -Values @{ Required = $true; Description = "Always the FIRST of the reporting month, e.g. 2026-08-01." }
    Add-PnPField -List $list -DisplayName "ItemNumber" -InternalName "ItemNumber" -Type Number -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "ScheduleItem" -InternalName "ScheduleItem" -Type Note -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "StatusCode" -InternalName "StatusCode" -Type Choice -Choices "ON_TRACK","BEHIND","AT_RISK" -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "CriticalDelays" -InternalName "CriticalDelays" -Type Note -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "RecoveryPlan" -InternalName "RecoveryPlan" -Type Note -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "ForecastImpact" -InternalName "ForecastImpact" -Type Note -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "Notes" -InternalName "Notes" -Type Note -AddToDefaultView | Out-Null
} catch [System.Management.Automation.RuntimeException] {
    # Add-PnPField throws if the column already exists. That is the idempotent
    # path, not a failure - anything else rethrows.
    if ($_.Exception.Message -notmatch 'already exists') { throw }
}

# --------------------------------------------------------------------------
# CD Flags  ->  man_Flags
$list = Ensure-List "CD Flags"
try {
    Add-PnPField -List $list -DisplayName "ProjectKey" -InternalName "ProjectKey" -Type Lookup -AddToDefaultView -ErrorAction Stop | Out-Null
    Set-PnPField -List $list -Identity "ProjectKey" -Values @{ LookupList = $projectsList.Id.ToString(); LookupField = "Title"; Required = $true }
    Add-PnPField -List $list -DisplayName "MonthStart" -InternalName "MonthStart" -Type DateTime -AddToDefaultView | Out-Null
    Set-PnPField -List $list -Identity "MonthStart" -Values @{ Required = $true; Description = "Always the FIRST of the reporting month, e.g. 2026-08-01." }
    Add-PnPField -List $list -DisplayName "ProfitabilityCode" -InternalName "ProfitabilityCode" -Type Choice -Choices "Within Range","Out of Range, but has a plan","Margin fade but no plan" -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "ContingencyRemaining" -InternalName "ContingencyRemaining" -Type Number -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "BaselineApproved" -InternalName "BaselineApproved" -Type Boolean -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "BaselineRevision" -InternalName "BaselineRevision" -Type Note -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "MonthEndClosedOut" -InternalName "MonthEndClosedOut" -Type Boolean -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "ForecastingInLine" -InternalName "ForecastingInLine" -Type Boolean -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "ResourcesUpdated" -InternalName "ResourcesUpdated" -Type Boolean -AddToDefaultView | Out-Null
} catch [System.Management.Automation.RuntimeException] {
    # Add-PnPField throws if the column already exists. That is the idempotent
    # path, not a failure - anything else rethrows.
    if ($_.Exception.Message -notmatch 'already exists') { throw }
}

# --------------------------------------------------------------------------
# CD Survey  ->  man_Survey
$list = Ensure-List "CD Survey"
try {
    Add-PnPField -List $list -DisplayName "ProjectKey" -InternalName "ProjectKey" -Type Lookup -AddToDefaultView -ErrorAction Stop | Out-Null
    Set-PnPField -List $list -Identity "ProjectKey" -Values @{ LookupList = $projectsList.Id.ToString(); LookupField = "Title"; Required = $true }
    Add-PnPField -List $list -DisplayName "MonthStart" -InternalName "MonthStart" -Type DateTime -AddToDefaultView | Out-Null
    Set-PnPField -List $list -Identity "MonthStart" -Values @{ Required = $true; Description = "Always the FIRST of the reporting month, e.g. 2026-08-01." }
    Add-PnPField -List $list -DisplayName "QuestionNumber" -InternalName "QuestionNumber" -Type Number -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "QuestionText" -InternalName "QuestionText" -Type Note -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "Score" -InternalName "Score" -Type Number -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "SurveyedParty" -InternalName "SurveyedParty" -Type Text -AddToDefaultView | Out-Null
} catch [System.Management.Automation.RuntimeException] {
    # Add-PnPField throws if the column already exists. That is the idempotent
    # path, not a failure - anything else rethrows.
    if ($_.Exception.Message -notmatch 'already exists') { throw }
}

# --------------------------------------------------------------------------
# CD SafetyMonthly  ->  man_SafetyMonthly
$list = Ensure-List "CD SafetyMonthly"
try {
    Add-PnPField -List $list -DisplayName "ProjectKey" -InternalName "ProjectKey" -Type Lookup -AddToDefaultView -ErrorAction Stop | Out-Null
    Set-PnPField -List $list -Identity "ProjectKey" -Values @{ LookupList = $projectsList.Id.ToString(); LookupField = "Title"; Required = $true }
    Add-PnPField -List $list -DisplayName "MonthStart" -InternalName "MonthStart" -Type DateTime -AddToDefaultView | Out-Null
    Set-PnPField -List $list -Identity "MonthStart" -Values @{ Required = $true; Description = "Always the FIRST of the reporting month, e.g. 2026-08-01." }
    Add-PnPField -List $list -DisplayName "HoursWorked" -InternalName "HoursWorked" -Type Number -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "RecordableIncidents" -InternalName "RecordableIncidents" -Type Number -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "Orientations" -InternalName "Orientations" -Type Number -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "OtHours" -InternalName "OtHours" -Type Number -AddToDefaultView | Out-Null
} catch [System.Management.Automation.RuntimeException] {
    # Add-PnPField throws if the column already exists. That is the idempotent
    # path, not a failure - anything else rethrows.
    if ($_.Exception.Message -notmatch 'already exists') { throw }
}

# --------------------------------------------------------------------------
# CD QualityMonthly  ->  man_QualityMonthly
$list = Ensure-List "CD QualityMonthly"
try {
    Add-PnPField -List $list -DisplayName "ProjectKey" -InternalName "ProjectKey" -Type Lookup -AddToDefaultView -ErrorAction Stop | Out-Null
    Set-PnPField -List $list -Identity "ProjectKey" -Values @{ LookupList = $projectsList.Id.ToString(); LookupField = "Title"; Required = $true }
    Add-PnPField -List $list -DisplayName "MonthStart" -InternalName "MonthStart" -Type DateTime -AddToDefaultView | Out-Null
    Set-PnPField -List $list -Identity "MonthStart" -Values @{ Required = $true; Description = "Always the FIRST of the reporting month, e.g. 2026-08-01." }
    Add-PnPField -List $list -DisplayName "Observations" -InternalName "Observations" -Type Number -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "PunchlistItems" -InternalName "PunchlistItems" -Type Number -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "AvgDaysPastDue" -InternalName "AvgDaysPastDue" -Type Number -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "AvgDaysToClose" -InternalName "AvgDaysToClose" -Type Number -AddToDefaultView | Out-Null
} catch [System.Management.Automation.RuntimeException] {
    # Add-PnPField throws if the column already exists. That is the idempotent
    # path, not a failure - anything else rethrows.
    if ($_.Exception.Message -notmatch 'already exists') { throw }
}

# --------------------------------------------------------------------------
# CD Milestones  ->  man_Milestones
$list = Ensure-List "CD Milestones"
try {
    Add-PnPField -List $list -DisplayName "ProjectKey" -InternalName "ProjectKey" -Type Lookup -AddToDefaultView -ErrorAction Stop | Out-Null
    Set-PnPField -List $list -Identity "ProjectKey" -Values @{ LookupList = $projectsList.Id.ToString(); LookupField = "Title"; Required = $true }
    Add-PnPField -List $list -DisplayName "ActivityKey" -InternalName "ActivityKey" -Type Text -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "MilestoneName" -InternalName "MilestoneName" -Type Text -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "ContractStart" -InternalName "ContractStart" -Type DateTime -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "ContractFinish" -InternalName "ContractFinish" -Type DateTime -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "BaselineStart" -InternalName "BaselineStart" -Type DateTime -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "BaselineFinish" -InternalName "BaselineFinish" -Type DateTime -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "IsSubstantialCompletion" -InternalName "IsSubstantialCompletion" -Type Boolean -AddToDefaultView | Out-Null
} catch [System.Management.Automation.RuntimeException] {
    # Add-PnPField throws if the column already exists. That is the idempotent
    # path, not a failure - anything else rethrows.
    if ($_.Exception.Message -notmatch 'already exists') { throw }
}

# --------------------------------------------------------------------------
# CD DailyLogCompliance  ->  man_DailyLogCompliance
$list = Ensure-List "CD DailyLogCompliance"
try {
    Add-PnPField -List $list -DisplayName "ProjectKey" -InternalName "ProjectKey" -Type Lookup -AddToDefaultView -ErrorAction Stop | Out-Null
    Set-PnPField -List $list -Identity "ProjectKey" -Values @{ LookupList = $projectsList.Id.ToString(); LookupField = "Title"; Required = $true }
    Add-PnPField -List $list -DisplayName "MonthStart" -InternalName "MonthStart" -Type DateTime -AddToDefaultView | Out-Null
    Set-PnPField -List $list -Identity "MonthStart" -Values @{ Required = $true; Description = "Always the FIRST of the reporting month, e.g. 2026-08-01." }
    Add-PnPField -List $list -DisplayName "LogsExpected" -InternalName "LogsExpected" -Type Number -AddToDefaultView | Out-Null
    Add-PnPField -List $list -DisplayName "LogsMissedSameDay" -InternalName "LogsMissedSameDay" -Type Number -AddToDefaultView | Out-Null
} catch [System.Management.Automation.RuntimeException] {
    # Add-PnPField throws if the column already exists. That is the idempotent
    # path, not a failure - anything else rethrows.
    if ($_.Exception.Message -notmatch 'already exists') { throw }
}

Write-Host ''
Write-Host 'Done. 9 lists plus CD Projects.'
Write-Host 'Next: populate CD Projects from dim_Project, then point'
Write-Host 'CD_Manual_Ingest at this site and run it.'
