"""Build, deploy and run cd_40_dq_checks - the gate between gold and the report.

    python deploy_dq.py            # dry run
    python deploy_dq.py --apply    # create/update the notebook and run it

Runs the expectations in 02-transformation/dq/expectations.py against gold, writes the
results to cd_dq_results and the offending rows to cd_dq_rejects, and RAISES on a blocking
failure.

WHY IT RAISES. A failure prevents Succeeded-dependent pipeline activities from running.
This alone does not isolate Direct Lake readers from gold writes or automatic updates;
publication isolation must be configured and verified separately.

Warnings do NOT raise. They are counted, persisted and printed. Blocking on a real business
condition - a project genuinely not yet in Sage - is how a pipeline gets muted within a
week, and a muted pipeline's blocking checks stop working too.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import deploy as dp  # noqa: E402
import deploy_gold as dg  # noqa: E402
import deploy_seeds as ds  # noqa: E402
from make_notebooks import cell, notebook  # noqa: E402

HERE = Path(__file__).resolve().parent
CHARLEY_DEV = HERE.parent
DQ_DIR = CHARLEY_DEV / "02-transformation" / "dq"

NOTEBOOK_NAME = "cd_40_dq_checks"

# Uploaded to the gold lakehouse so the notebook imports the SAME code the offline suite
# asserts - not a copy that can drift.
UPLOADS = [
    (CHARLEY_DEV / "00-platform" / "lib" / "dq.py", "Files/lib/dq.py"),
    (DQ_DIR / "expectations.py", "Files/lib/expectations.py"),
    # The gate imports fabric_common for notify(). The GOLD lakehouse has its own Files/lib
    # - deploy_ingestion uploads to BRONZE - so shipping it here is not redundant, and
    # leaving it out fails the gate with ModuleNotFoundError on the first run.
    (CHARLEY_DEV / "00-platform" / "lib" / "fabric_common.py", "Files/lib/fabric_common.py"),
]


def source_view_statements() -> list[str]:
    """The sv_* views cd_30_build_gold creates: same file, placeholders and splitter."""
    sql = (dg.SOURCES[dg.DEFAULT_SOURCE].read_text(encoding="utf-8")
           .replace("{SILVER_ABFSS}", dg.SILVER_ABFSS)
           .replace("{CD_SILVER_ABFSS}", dg.CD_SILVER_ABFSS))
    return dg.statements(sql)


def build_notebook() -> dict:
    cells = [
        cell(
            f"""
# {NOTEBOOK_NAME}

Runs the data-quality expectations against **CD_Gold_Lakehouse** and fails the pipeline on
a blocking violation.

Generated by `_local/deploy_dq.py` - edit `02-transformation/dq/expectations.py`, not this
notebook.

`ERROR` stops the run. Direct Lake publication isolation must be verified separately.
`WARN` is recorded and continues. The difference is deliberate: a
wrong number published silently is worse than a stale one, and a pipeline that blocks on
real business conditions gets muted.
""",
            "markdown",
        ),
        cell(
            '''
import json, os, sys
from datetime import datetime, timezone

sys.path.insert(0, "/lakehouse/default/Files/lib")
import dq
import fabric_common as fc
from expectations import build_suite, summarise

DIAG = "/lakehouse/default/Files/_diag"
os.makedirs(DIAG, exist_ok=True)

batch_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
suite = build_suite()
print(f"{len(suite.expectations)} expectation(s), batch {batch_id}\\n")

# Same read settings as cd_30_build_gold: the submittals Parquet holds pre-1582 placeholder
# dates Spark 3 otherwise refuses to read.
spark.conf.set("spark.sql.parquet.datetimeRebaseModeInRead", "CORRECTED")
spark.conf.set("spark.sql.parquet.int96RebaseModeInRead", "CORRECTED")

# The sv_* source views, registered before any rule runs. Temp views die with the gold
# notebook's session, and several rules read them. A failure here raises with its cause,
# rather than surfacing later as "could not run".
SOURCE_VIEWS = ''' + json.dumps(source_view_statements(), indent=1) + '''
for _sql in SOURCE_VIEWS:
    spark.sql(_sql)
print(f"{len(SOURCE_VIEWS)} source view(s) registered")
'''
        ),
        cell(
            '''
# EVALUATE FIRST, PERSIST SECOND.
#
# suite.run(persist=True) writes cd_dq_results and cd_dq_rejects as part of the same call,
# so a failure in the WRITE loses the whole evaluation - the notebook reports "failed" and
# no diagnostics exist to say what was actually checked. Diagnostics have to survive a
# persistence failure, because persistence failing is itself something you need to see.
results = suite.run(spark, batch_id, persist=False)
print(summarise(results))

# Written before the raise, so a blocking failure is diagnosable rather than just loud.
# The Fabric jobs API reports "failed" with no cell detail, so this file is the only
# account of WHICH expectation fired and how many rows.
payload = [{"name": r.expectation.name,
            "table": r.expectation.table,
            "severity": r.expectation.severity,
            "description": r.expectation.description,
            "failing_rows": r.failing_rows,
            "passed": r.passed,
            "blocking": r.blocking}
           for r in results]
with open(f"{DIAG}/dq_run.json", "w", encoding="utf-8") as fh:
    json.dump({"batch": batch_id, "results": payload}, fh, indent=1)
print(f"diagnostics written: {len(payload)} expectation(s)")

# Now persist to the lakehouse tables the report reads. Failing here is worth knowing about
# but must not discard an evaluation that already succeeded.
try:
    dq._persist_results(spark, results, batch_id)
    for r in results:
        if r.failing_rows > 0:
            dq._persist_rejects(spark, r.expectation,
                                spark.sql(r.expectation.failing_sql), batch_id)
    print("results and rejects persisted to cd_dq_results / cd_dq_rejects")
except Exception as exc:
    print(f"PERSIST FAILED ({type(exc).__name__}: {exc}) - "
          f"evaluation stands, see Files/_diag/dq_run.json")
    raise RuntimeError("DQ evidence could not be persisted; pipeline blocked; reader isolation is a separate requirement") from exc

# ---------------------------------------------------------------- heartbeat
#
# One row per run of this gate. Written LAST, and only once the evaluation above has
# actually happened, so a row here means the whole medallion reached the end and the
# numbers were checked - not merely that something started.
#
# This is the alerting the platform has. Active alerting (email, Teams) needs a
# credentialed connector nobody has set up; this needs nothing. If any upstream stage
# fails, this cell never runs, no row is written, and [Hours Since Last Checked Run] on the
# report climbs until somebody notices. Absence of a heartbeat is the signal.
#
# APPEND, never overwrite: the history is what makes "it has been failing since Tuesday"
# answerable, and that is usually the more useful question than "is it broken now".
try:
    dq.persist_heartbeat(spark, results, batch_id, DIAG)
except Exception as exc:
    raise RuntimeError("DQ heartbeat could not be persisted; pipeline blocked; reader isolation is a separate requirement") from exc
'''
        ),
        cell(
            '''
# A check that could not RUN is treated as a failure, not ignored. A broken expectation is
# indistinguishable from a passing one if you only count failing rows, and that is how a
# suite quietly stops testing anything.
broken = [r for r in results if r.failing_rows < 0]
if broken:
    raise AssertionError(
        f"{len(broken)} expectation(s) could not run - the checks themselves are broken:\\n  "
        + "\\n  ".join(r.expectation.name for r in broken))

# ALERT BEFORE RAISING. assert_no_blocking raises, and anything after a raise does not run -
# so a notification placed below it would fire on every outcome except the one that needs it.
blocking_results = [r for r in results if r.blocking]
if blocking_results:
    fc.notify(
        f"DQ GATE FAILED - {len(blocking_results)} blocking failure(s)",
        "The nightly data-quality gate failed. "
        "Validation failed; inspect the persisted results before using this run.\\n\\n"
        + "\\n".join(f"- {r.expectation.name}: {r.failing_rows} row(s) - "
                     f"{r.expectation.description}" for r in blocking_results[:10]),
        failing=len(blocking_results))

dq.assert_no_blocking(results)

warnings = [r for r in results if not r.passed and not r.blocking]
if warnings:
    print(f"\\n{len(warnings)} warning(s) recorded to cd_dq_results - not blocking.")
    print("These are integration gaps to act on, not pipeline defects:")
    for r in warnings:
        print(f"  {r.expectation.name}: {r.failing_rows} row(s) - {r.expectation.description}")

print("\\nall blocking expectations passed - publication controls and source coverage still require verification")
'''
        ),
    ]
    return notebook(cells)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    tok = dp.token()
    lh = json.loads((HERE / "fabric_ids.json").read_text())["CD_Gold_Lakehouse"]
    print(f"gold lakehouse {lh['id']}")

    for local, remote in UPLOADS:
        if not local.exists():
            print(f"  MISSING {local}")
            return 1
        print(f"  {remote:<32} {local.stat().st_size:>7,} bytes")

    nb = ds.attach(build_notebook(), lh, dp.WORKSPACE_ID)
    nb["metadata"]["dependencies"]["lakehouse"]["default_lakehouse_name"] = "CD_Gold_Lakehouse"

    existing = ds.find_item(tok, NOTEBOOK_NAME, "Notebook")
    print(f"\nwould {'update' if existing else 'create'} {NOTEBOOK_NAME} and run it")

    if not args.apply:
        print("\nDRY RUN - nothing written. Re-run with --apply.")
        return 0

    # Upload the library alongside the notebook, so the deployed checks are always the ones
    # the offline suite verified.
    import deploy_ingestion as di

    stok = di.storage_token()
    for local, remote in UPLOADS:
        di.upload(lh["id"], stok, local, remote)
        print(f"  uploaded {remote}")

    definition = {"format": "ipynb", "parts": [
        {"path": "notebook-content.ipynb", "payload": ds.payload(nb),
         "payloadType": "InlineBase64"}]}

    if existing:
        status, _, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items/{existing['id']}/updateDefinition",
            tok, {"definition": definition})
        if status == 202:
            dp.wait_for_operation(headers, tok)
        item_id = existing["id"]
        print(f"  updated {NOTEBOOK_NAME}")
    else:
        status, _, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items", tok,
            {"displayName": NOTEBOOK_NAME, "type": "Notebook",
             "folderId": dp.FOLDER_ID, "definition": definition})
        if status == 202:
            dp.wait_for_operation(headers, tok)
        item_id = ds.find_item(tok, NOTEBOOK_NAME, "Notebook")["id"]
        print(f"  created {NOTEBOOK_NAME} ({item_id})")

    print("  running ...", end=" ", flush=True)
    print(ds.run_notebook(tok, item_id))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except dp.FabricError as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
