"""Build, deploy and run cd_05_land_to_bronze - files in, Delta out, no credentials.

    python deploy_landing.py            # dry run
    python deploy_landing.py --apply    # create/update the notebook and run it
    python deploy_landing.py --apply --batch 20260802T043000Z   # a specific batch

`extract_procore_local.py` lands raw NDJSON in `CD_Bronze_Lakehouse/Files/_landing/<batch>/`.
This notebook merges those files into the `cd_bronze_procore_*` Delta tables.

The split is the point: extraction needs a Procore secret and runs locally, where the secret
already lives; this half needs Spark and runs in Fabric, where it needs no secret at all.
Nothing reaches the workspace except data - which is what stops us recreating finding F1 in
_docs/security-findings.md while trying to fix it.

It is also the piece that does not change when Key Vault arrives. `cd_01_extract_procore`
will write the same bronze tables directly, and this notebook keeps working, because all it
ever does is read files that are already there.

MERGE, NOT APPEND. Re-running a batch must be a no-op, not a duplicate - that is the whole
reason `merge_delta` exists rather than the `DROP TABLE` + append the foundation notebooks
use. The merge key is `_key` plus `_project_id`, combined into one non-null `_merge_key`
column first: a Delta MERGE predicate of `t._project_id = s._project_id` never matches when
both sides are NULL, so company-scoped endpoints would re-insert every row on every run.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import deploy as dp  # noqa: E402
import deploy_seeds as ds  # noqa: E402
from make_notebooks import cell, notebook  # noqa: E402

HERE = Path(__file__).resolve().parent
CHARLEY_DEV = HERE.parent

NOTEBOOK_NAME = "cd_05_land_to_bronze"

# The bronze contract silver reads. _source_endpoint rides along as provenance; silver
# selects columns explicitly, so an extra one is harmless and an absent one is not.
BRONZE_COLUMNS = ["_key", "_project_id", "payload", "_ingested_at", "_batch_id",
                  "_row_hash", "_source_endpoint"]


def build_notebook(batch: str | None) -> dict:
    chosen = f'"{batch}"' if batch else "None"

    cells = [
        cell(
            f"""
# {NOTEBOOK_NAME}

Merges the raw Procore payloads landed in `Files/_landing/<batch>/` into the
`cd_bronze_procore_*` Delta tables in **CD_Bronze_Lakehouse**.

Generated by `_local/deploy_landing.py` - edit that, not this notebook.

**This notebook holds no credentials and needs none.** The Procore call happens in
`_local/extract_procore_local.py`, on a machine that already has the secret. See
`_docs/procore-ingestion.md` for why the pipeline is split that way and what changes when
Key Vault becomes available.
""",
            "markdown",
        ),
        cell(
            f'''
import json, os, sys, traceback
from pyspark.sql import functions as F

sys.path.insert(0, "/lakehouse/default/Files/lib")
from fabric_common import merge_sql          # the tested MERGE builder, not a second copy

DIAG = "/lakehouse/default/Files/_diag"
LANDING = "/lakehouse/default/Files/_landing"
os.makedirs(DIAG, exist_ok=True)

BATCH = {chosen}

if not os.path.isdir(LANDING):
    raise AssertionError(
        "Files/_landing does not exist. Run _local/extract_procore_local.py --apply first; "
        "see _docs/procore-ingestion.md.")

batches = sorted(b for b in os.listdir(LANDING) if not b.startswith("_"))
if not batches:
    raise AssertionError("Files/_landing is empty - nothing has been extracted yet.")

batch = BATCH or batches[-1]      # newest by name; the batch id is a UTC timestamp
if batch not in batches:
    raise AssertionError(f"batch {{batch!r}} not found. Available: {{batches}}")

with open(f"{{LANDING}}/{{batch}}/_manifest.json", encoding="utf-8") as fh:
    manifest = json.load(fh)

print(f"batch {{batch}}  host {{manifest['host']}}  {{manifest['projects']}} project(s)")
print(f"{{len(manifest['endpoints'])}} endpoint file(s), "
      f"{{manifest['total_rows']}} row(s) extracted, "
      f"{{len(manifest.get('failures', []))}} endpoint(s) failed at extract time")
'''
        ),
        cell(
            f'''
results, landed = [], {{}}

for entry in manifest["endpoints"]:
    table, rows_expected = entry["table"], entry["rows"]
    path = f"Files/_landing/{{batch}}/{{table}}.jsonl"

    if rows_expected == 0:
        # A genuinely empty endpoint. Skip rather than fail - a company with no change
        # orders has no change orders, and that is data, not an error.
        results.append({{"table": table, "ok": True, "rows": 0, "note": "empty at source"}})
        landed[table] = 0
        continue

    try:
        df = spark.read.json(path)

        # _project_id arrives as a JSON number and must be a string to match the bronze
        # contract silver parses. _row_hash is computed here rather than locally so it is
        # derived from exactly the bytes that landed.
        df = (df
              .withColumn("_ingested_at", F.to_timestamp("_ingested_at"))
              .withColumn("_project_id", F.col("_project_id").cast("string"))
              .withColumn("_row_hash", F.sha2(F.col("payload"), 256))
              .withColumn("_merge_key",
                          F.concat_ws("|", F.col("_key"),
                                      F.coalesce(F.col("_project_id"), F.lit("")))))

        for col in {BRONZE_COLUMNS!r}:
            if col not in df.columns:
                df = df.withColumn(col, F.lit(None).cast("string"))

        cols = {BRONZE_COLUMNS!r} + ["_merge_key"]
        df = df.select(*cols)

        if not spark.catalog.tableExists(table):
            # First landing. overwriteSchema so the table is created WITH data files -
            # a schema-only CREATE TABLE writes none, and nothing downstream can bind to it.
            df.write.format("delta").mode("overwrite") \\
              .option("overwriteSchema", "true").saveAsTable(table)
            note = "created"
        else:
            df.createOrReplaceTempView("staged")
            spark.sql(merge_sql(table, "staged", ["_merge_key"], cols))
            note = "merged"

        actual = spark.sql(f"SELECT COUNT(*) AS n FROM {{table}}").collect()[0]["n"]
        landed[table] = actual
        results.append({{"table": table, "ok": True, "rows": actual,
                         "extracted": rows_expected, "note": note}})
        print(f"  {{table:<44}} {{actual:>7}} rows  ({{note}})")

    except Exception as exc:
        results.append({{"table": table, "ok": False,
                         "error": f"{{type(exc).__name__}}: {{exc}}"[:1200]}})
        print(f"  {{table:<44}} FAILED  {{type(exc).__name__}}: {{str(exc)[:200]}}")
'''
        ),
        cell(
            """
with open(f"{DIAG}/landing_run.json", "w", encoding="utf-8") as fh:
    json.dump({"batch": batch, "results": results}, fh, indent=1)

failed = [r for r in results if not r["ok"]]
total = sum(landed.values())

print(f"\\n{total} row(s) across {len(landed)} bronze table(s)")

if failed:
    raise AssertionError(
        f"{len(failed)} table(s) failed to land:\\n  "
        + "\\n  ".join(f"{r['table']}: {r['error'][:200]}" for r in failed[:8]))

# Loud, because the alternative is a silver run that quietly produces nothing and a gold
# rebuild that publishes empty tables over working ones.
if total == 0:
    raise AssertionError(
        "every bronze table is empty. The extract landed files but none held rows - "
        "check _manifest.json failures in Files/_landing/<batch>/.")

print("bronze is populated. Next: run cd_10_bronze_to_silver, then cd_30_build_gold.")
"""
        ),
    ]
    return notebook(cells)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--batch", default="", help="a specific batch id (default: newest)")
    args = parser.parse_args()

    tok = dp.token()
    ids = json.loads((HERE / "fabric_ids.json").read_text())
    lh = ids["CD_Bronze_Lakehouse"]
    print(f"bronze lakehouse {lh['id']}")
    print(f"batch: {args.batch or '(newest in Files/_landing)'}")

    nb = ds.attach(build_notebook(args.batch or None), lh, dp.WORKSPACE_ID)
    nb["metadata"]["dependencies"]["lakehouse"]["default_lakehouse_name"] = "CD_Bronze_Lakehouse"

    existing = ds.find_item(tok, NOTEBOOK_NAME, "Notebook")
    print(f"would {'update' if existing else 'create'} {NOTEBOOK_NAME} "
          f"({len(nb['cells'])} cells) and run it")

    if not args.apply:
        print("\nDRY RUN - nothing written. Re-run with --apply.")
        return 0

    definition = {"format": "ipynb", "parts": [
        {"path": "notebook-content.ipynb", "payload": ds.payload(nb),
         "payloadType": "InlineBase64"}]}

    if existing:
        status, _, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items/{existing['id']}/updateDefinition",
            tok, {"definition": definition})
        if status == 202:
            dp.wait_for_operation(headers, tok)
        item_id = existing["id"]
        print(f"  updated {NOTEBOOK_NAME}")
    else:
        status, _, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items", tok,
            {"displayName": NOTEBOOK_NAME, "type": "Notebook",
             "folderId": dp.FOLDER_ID, "definition": definition})
        if status == 202:
            dp.wait_for_operation(headers, tok)
        item_id = ds.find_item(tok, NOTEBOOK_NAME, "Notebook")["id"]
        print(f"  created {NOTEBOOK_NAME} ({item_id})")

    print("  running ...", end=" ", flush=True)
    print(ds.run_notebook(tok, item_id))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except dp.FabricError as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
