"""Build, deploy and run cd_40_dq_checks - the gate between gold and the report.

    python deploy_dq.py            # dry run
    python deploy_dq.py --apply    # create/update the notebook and run it

Runs the 34 expectations in 02-transformation/dq/expectations.py against gold, writes the
results to cd_dq_results and the offending rows to cd_dq_rejects, and RAISES on a blocking
failure.

WHY IT RAISES. CD_Master_Pipeline gates on "Succeeded", so a raise here stops the semantic
model from refreshing and the report keeps yesterday's numbers. That looks drastic until
you consider the alternative: leadership opens the report, the numbers are today's and
wrong, and nothing on the page says so. The workbook's defects survived for months
precisely because nothing ever refused to publish.

Warnings do NOT raise. They are counted, persisted and printed. Blocking on a real business
condition - a project genuinely not yet in Sage - is how a pipeline gets muted within a
week, and a muted pipeline's blocking checks stop working too.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import deploy as dp  # noqa: E402
import deploy_seeds as ds  # noqa: E402
from make_notebooks import cell, notebook  # noqa: E402

HERE = Path(__file__).resolve().parent
CHARLEY_DEV = HERE.parent
DQ_DIR = CHARLEY_DEV / "02-transformation" / "dq"

NOTEBOOK_NAME = "cd_40_dq_checks"

# Uploaded to the gold lakehouse so the notebook imports the SAME code the offline suite
# asserts - not a copy that can drift.
UPLOADS = [
    (CHARLEY_DEV / "00-platform" / "lib" / "dq.py", "Files/lib/dq.py"),
    (DQ_DIR / "expectations.py", "Files/lib/expectations.py"),
]


def build_notebook() -> dict:
    cells = [
        cell(
            f"""
# {NOTEBOOK_NAME}

Runs the data-quality expectations against **CD_Gold_Lakehouse** and fails the pipeline on
a blocking violation.

Generated by `_local/deploy_dq.py` - edit `02-transformation/dq/expectations.py`, not this
notebook.

`ERROR` stops the run, so the semantic model is not refreshed and the report keeps
yesterday's numbers. `WARN` is recorded and continues. The difference is deliberate: a
wrong number published silently is worse than a stale one, and a pipeline that blocks on
real business conditions gets muted.
""",
            "markdown",
        ),
        cell(
            '''
import json, os, sys
from datetime import datetime, timezone

sys.path.insert(0, "/lakehouse/default/Files/lib")
import dq
from expectations import build_suite, summarise

DIAG = "/lakehouse/default/Files/_diag"
os.makedirs(DIAG, exist_ok=True)

batch_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
suite = build_suite()
print(f"{len(suite.expectations)} expectation(s), batch {batch_id}\\n")
'''
        ),
        cell(
            '''
# EVALUATE FIRST, PERSIST SECOND.
#
# suite.run(persist=True) writes cd_dq_results and cd_dq_rejects as part of the same call,
# so a failure in the WRITE loses the whole evaluation - the notebook reports "failed" and
# no diagnostics exist to say what was actually checked. Diagnostics have to survive a
# persistence failure, because persistence failing is itself something you need to see.
results = suite.run(spark, batch_id, persist=False)
print(summarise(results))

# Written before the raise, so a blocking failure is diagnosable rather than just loud.
# The Fabric jobs API reports "failed" with no cell detail, so this file is the only
# account of WHICH expectation fired and how many rows.
payload = [{"name": r.expectation.name,
            "table": r.expectation.table,
            "severity": r.expectation.severity,
            "description": r.expectation.description,
            "failing_rows": r.failing_rows,
            "passed": r.passed,
            "blocking": r.blocking}
           for r in results]
with open(f"{DIAG}/dq_run.json", "w", encoding="utf-8") as fh:
    json.dump({"batch": batch_id, "results": payload}, fh, indent=1)
print(f"diagnostics written: {len(payload)} expectation(s)")

# Now persist to the lakehouse tables the report reads. Failing here is worth knowing about
# but must not discard an evaluation that already succeeded.
try:
    dq._persist_results(spark, results, batch_id)
    for r in results:
        if r.failing_rows > 0:
            dq._persist_rejects(spark, r.expectation,
                                spark.sql(r.expectation.failing_sql), batch_id)
    print("results and rejects persisted to cd_dq_results / cd_dq_rejects")
except Exception as exc:
    print(f"PERSIST FAILED ({type(exc).__name__}: {exc}) - "
          f"evaluation stands, see Files/_diag/dq_run.json")

# ---------------------------------------------------------------- heartbeat
#
# One row per run of this gate. Written LAST, and only once the evaluation above has
# actually happened, so a row here means the whole medallion reached the end and the
# numbers were checked - not merely that something started.
#
# This is the alerting the platform has. Active alerting (email, Teams) needs a
# credentialed connector nobody has set up; this needs nothing. If any upstream stage
# fails, this cell never runs, no row is written, and [Hours Since Last Checked Run] on the
# report climbs until somebody notices. Absence of a heartbeat is the signal.
#
# APPEND, never overwrite: the history is what makes "it has been failing since Tuesday"
# answerable, and that is usually the more useful question than "is it broken now".
try:
    from pyspark.sql import Row
    from datetime import datetime, timezone

    failing = sum(1 for r in results if r.failing_rows > 0)
    blocking = sum(1 for r in results if r.blocking)
    heartbeat = spark.createDataFrame([Row(
        RunId=batch_id,
        RunAt=datetime.now(timezone.utc).replace(tzinfo=None),
        Stage="dq_gate",
        Status="blocked" if blocking else "ok",
        Expectations=len(results),
        Failing=failing,
        Blocking=blocking,
    )])
    heartbeat.write.format("delta").mode("append").saveAsTable("meta_PipelineRun")
    print(f"heartbeat written: {batch_id} "
          f"({len(results)} expectations, {failing} failing, {blocking} blocking)")
except Exception as exc:
    # A failed heartbeat must not fail the run - it is a monitoring aid, and taking the
    # pipeline down to protect the thing that watches the pipeline is backwards.
    print(f"HEARTBEAT FAILED ({type(exc).__name__}: {exc}) - the run itself is unaffected")
'''
        ),
        cell(
            '''
# A check that could not RUN is treated as a failure, not ignored. A broken expectation is
# indistinguishable from a passing one if you only count failing rows, and that is how a
# suite quietly stops testing anything.
broken = [r for r in results if r.failing_rows < 0]
if broken:
    raise AssertionError(
        f"{len(broken)} expectation(s) could not run - the checks themselves are broken:\\n  "
        + "\\n  ".join(r.expectation.name for r in broken))

dq.assert_no_blocking(results)

warnings = [r for r in results if not r.passed and not r.blocking]
if warnings:
    print(f"\\n{len(warnings)} warning(s) recorded to cd_dq_results - not blocking.")
    print("These are integration gaps to act on, not pipeline defects:")
    for r in warnings:
        print(f"  {r.expectation.name}: {r.failing_rows} row(s) - {r.expectation.description}")

print("\\nall blocking expectations passed - safe to refresh the model")
'''
        ),
    ]
    return notebook(cells)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    tok = dp.token()
    lh = json.loads((HERE / "fabric_ids.json").read_text())["CD_Gold_Lakehouse"]
    print(f"gold lakehouse {lh['id']}")

    for local, remote in UPLOADS:
        if not local.exists():
            print(f"  MISSING {local}")
            return 1
        print(f"  {remote:<32} {local.stat().st_size:>7,} bytes")

    nb = ds.attach(build_notebook(), lh, dp.WORKSPACE_ID)
    nb["metadata"]["dependencies"]["lakehouse"]["default_lakehouse_name"] = "CD_Gold_Lakehouse"

    existing = ds.find_item(tok, NOTEBOOK_NAME, "Notebook")
    print(f"\nwould {'update' if existing else 'create'} {NOTEBOOK_NAME} and run it")

    if not args.apply:
        print("\nDRY RUN - nothing written. Re-run with --apply.")
        return 0

    # Upload the library alongside the notebook, so the deployed checks are always the ones
    # the offline suite verified.
    import deploy_ingestion as di

    stok = di.storage_token()
    for local, remote in UPLOADS:
        di.upload(lh["id"], stok, local, remote)
        print(f"  uploaded {remote}")

    definition = {"format": "ipynb", "parts": [
        {"path": "notebook-content.ipynb", "payload": ds.payload(nb),
         "payloadType": "InlineBase64"}]}

    if existing:
        status, _, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items/{existing['id']}/updateDefinition",
            tok, {"definition": definition})
        if status == 202:
            dp.wait_for_operation(headers, tok)
        item_id = existing["id"]
        print(f"  updated {NOTEBOOK_NAME}")
    else:
        status, _, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items", tok,
            {"displayName": NOTEBOOK_NAME, "type": "Notebook",
             "folderId": dp.FOLDER_ID, "definition": definition})
        if status == 202:
            dp.wait_for_operation(headers, tok)
        item_id = ds.find_item(tok, NOTEBOOK_NAME, "Notebook")["id"]
        print(f"  created {NOTEBOOK_NAME} ({item_id})")

    print("  running ...", end=" ", flush=True)
    print(ds.run_notebook(tok, item_id))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except dp.FabricError as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
