"""Build and deploy cd_50_publish_models - the only thing that shows readers a new gold.

    python deploy_publish.py                # dry run
    python deploy_publish.py --apply        # create/update the notebook (does NOT run it)
    python deploy_publish.py --apply --run  # ...and run it now: an out-of-band publish

WHY THIS EXISTS. Both models are Direct Lake on OneLake. Readers see the gold Delta tables
as of the model's last framing. With automatic update ON, the service frames on its own as
soon as gold is written - before the DQ gate has looked at it, and per table, so mid-build a
report can mix two releases. set_autosync.py turns that off; this notebook is then the one
place a frame happens, and the pipeline runs it only after "Data Quality Gate" Succeeded.

WHAT IT DOES, IN ORDER, FAILING LOUDLY:
  1. Full refresh of "Affect Project Report", wait for THAT request (matched by requestId).
  2. Only then "Project Quality Plan". Serial, so a failure on model 1 leaves model 2 on the
     previous frame - both still showing the same (old) release.
  3. Reads the latest meta_PipelineRun RunId from each model. They must be equal, and equal
     to the gate run that just wrote Files/_diag/heartbeat_run.json. A mismatch means the
     two models disagree about which release they show.
  4. Writes Files/_diag/publish_run.json before raising, so a failure is diagnosable.

--run is deliberately separate from --apply: running it outside the pipeline frames
whatever gold holds right now, validated or not.
"""

from __future__ import annotations

import argparse
import inspect
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import deploy as dp  # noqa: E402
import deploy_seeds as ds  # noqa: E402
import validate_model as vm  # noqa: E402
from make_notebooks import cell, notebook  # noqa: E402

HERE = Path(__file__).resolve().parent
NOTEBOOK_NAME = "cd_50_publish_models"

# Order matters: see step 2 above.
MODELS = [
    ("Affect Project Report", "4cdfb689-232a-4f33-a6bf-d53e90e8025a"),
    ("Project Quality Plan", "4b208da4-ca20-450d-bb1b-c7e542b5bb2c"),
]
REFRESH_TIMEOUT = 900

RUN_ID_DAX = """EVALUATE
VAR Last = MAX ( meta_PipelineRun[RunAt] )
RETURN ROW ( "RunId", CALCULATE ( MAX ( meta_PipelineRun[RunId] ), meta_PipelineRun[RunAt] = Last ) )"""


def build_notebook() -> dict:
    # The SAME functions validate_model.py uses and test_validation.py exercises - copied in
    # by source, not rewritten, so the notebook cannot drift from the tested behaviour.
    helpers = "\n\n".join(inspect.getsource(f) for f in (vm.dax, vm.reframe, vm.wait_refresh))
    cells = [
        cell(
            f"""
# {NOTEBOOK_NAME}

Frames both Direct Lake models on the gold that the DQ gate just passed, then checks both
models show the same pipeline run. Generated by `_local/deploy_publish.py`.
""",
            "markdown",
        ),
        cell(
            '''
import json, os, urllib.error, urllib.request
from datetime import datetime, timezone
from types import SimpleNamespace

dp = SimpleNamespace(FabricError=RuntimeError)
PBI_API = "https://api.powerbi.com/v1.0/myorg/groups/''' + dp.WORKSPACE_ID + '''"
MODELS = ''' + json.dumps(MODELS) + '''
RUN_ID_DAX = ''' + json.dumps(RUN_ID_DAX) + '''
DIAG = "/lakehouse/default/Files/_diag"

''' + helpers
        ),
        cell(
            '''
tok = notebookutils.credentials.getToken("pbi")
record = {"started": datetime.now(timezone.utc).isoformat(), "models": [], "ok": False}
os.makedirs(DIAG, exist_ok=True)

def save():
    with open(f"{DIAG}/publish_run.json", "w", encoding="utf-8") as fh:
        json.dump(record, fh, indent=1, default=str)

try:
    for name, dataset_id in MODELS:
        print(f"refreshing {name} ...", flush=True)
        entry = {"name": name, "id": dataset_id}
        record["models"].append(entry)
        entry["refresh"] = reframe(dataset_id, tok, timeout=''' + str(REFRESH_TIMEOUT) + ''')
        print(f"  {entry['refresh'].get('status')} {entry['refresh'].get('requestId')}")
    for entry in record["models"]:
        entry["run_id"] = dax(entry["id"], tok, RUN_ID_DAX)[0].get("[RunId]")
        print(f"  {entry['name']}: meta_PipelineRun RunId {entry['run_id']}")
    with open(f"{DIAG}/heartbeat_run.json", encoding="utf-8") as fh:
        record["gate_run_id"] = json.load(fh)["run_id"]
    run_ids = {e["run_id"] for e in record["models"]}
    if None in run_ids or run_ids != {record["gate_run_id"]}:
        raise RuntimeError(f"models are on different releases: {[(e['name'], e['run_id']) for e in record['models']]}"
                           f" vs gate run {record['gate_run_id']}")
    record["ok"] = True
except Exception as exc:
    record["error"] = f"{type(exc).__name__}: {exc}"
    raise
finally:
    record["finished"] = datetime.now(timezone.utc).isoformat()
    save()

print(f"published run {record['gate_run_id']} to {len(MODELS)} model(s)")
'''
        ),
    ]
    return notebook(cells)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--run", action="store_true", help="also run it now (out-of-band publish)")
    args = parser.parse_args()

    tok = dp.token()
    lh = json.loads((HERE / "fabric_ids.json").read_text())["CD_Gold_Lakehouse"]
    nb = ds.attach(build_notebook(), lh, dp.WORKSPACE_ID)
    nb["metadata"]["dependencies"]["lakehouse"]["default_lakehouse_name"] = "CD_Gold_Lakehouse"

    existing = ds.find_item(tok, NOTEBOOK_NAME, "Notebook")
    print(f"would {'update' if existing else 'create'} {NOTEBOOK_NAME} "
          f"(refreshes {', '.join(n for n, _ in MODELS)})")
    if not args.apply:
        print("\nDRY RUN - nothing written. Re-run with --apply.")
        return 0

    definition = {"format": "ipynb", "parts": [
        {"path": "notebook-content.ipynb", "payload": ds.payload(nb),
         "payloadType": "InlineBase64"}]}
    if existing:
        status, _, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items/{existing['id']}/updateDefinition",
            tok, {"definition": definition})
        if status == 202:
            dp.wait_for_operation(headers, tok)
        item_id = existing["id"]
        print(f"  updated {NOTEBOOK_NAME}")
    else:
        status, _, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items", tok,
            {"displayName": NOTEBOOK_NAME, "type": "Notebook",
             "folderId": dp.FOLDER_ID, "definition": definition})
        if status == 202:
            dp.wait_for_operation(headers, tok)
        item_id = ds.find_item(tok, NOTEBOOK_NAME, "Notebook")["id"]
        print(f"  created {NOTEBOOK_NAME} ({item_id})")

    if args.run:
        print("  running ...", end=" ", flush=True)
        print(ds.run_notebook(tok, item_id))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except dp.FabricError as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
