"""Build, deploy and run the gold seed notebook in Fabric.

End to end: generate a notebook that inlines the seed SQL, create it in charley-dev
attached to CD_Gold_Lakehouse, run it, then verify the tables exist.

    python deploy_seeds.py            # dry run
    python deploy_seeds.py --apply    # create + run
    python deploy_seeds.py --verify   # list the gold tables that exist

The SQL is INLINED into the notebook rather than read from Files/. That keeps this
runnable with no separate upload step, and the notebook stays generated - the .sql files
remain the single source of truth, and regenerating picks up any edit.
"""

from __future__ import annotations

import argparse
import base64
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import deploy as dp  # noqa: E402
from make_notebooks import cell, notebook  # noqa: E402
from seedrunner import seed_files  # noqa: E402

HERE = Path(__file__).resolve().parent
NOTEBOOK_NAME = "cd_20_seed_gold"
IDS = HERE / "fabric_ids.json"


def lakehouse() -> dict:
    ids = json.loads(IDS.read_text())
    lh = ids["CD_Gold_Lakehouse"]
    assert lh["defaultSchema"] == "dbo", "gold lakehouse is not schema-enabled"
    return lh


def build_notebook() -> dict:
    """Generate the seed notebook, one cell per .sql file."""
    cells = [
        cell(
            f"""
# {NOTEBOOK_NAME}

Builds the gold seed dimensions in **CD_Gold_Lakehouse**.

Generated by `_local/deploy_seeds.py` from the `.sql` files - do not edit here, edit the
SQL and regenerate. The same SQL is verified offline by
`_local/tests/test_seeds.py` (33 assertions) before it ever reaches Fabric.
""",
            "markdown",
        ),
        cell(
            """
# dim_Status unions its static rows with Procore's own status vocabulary, which has not
# been ingested yet. Empty stubs let the static block build now; the real tables replace
# them when cd_01_extract_procore runs.
for ddl in [
    "CREATE TABLE IF NOT EXISTS bronze_procore_rfi_statuses (payload STRING)",
    "CREATE TABLE IF NOT EXISTS silver_rfi_submittal (ItemType STRING, StatusLabel STRING)",
]:
    spark.sql(ddl)

built = []
"""
        ),
    ]

    for path in seed_files():
        statements = [
            s.strip()
            for s in "\n".join(
                line.split("--", 1)[0] for line in path.read_text(encoding="utf-8").splitlines()
            ).split(";")
            if s.strip()
        ]
        body = "\n".join(
            f"spark.sql({json.dumps(s)})\n" for s in statements
        )
        cells.append(cell(f'# --- {path.name} ---\n{body}\nprint("{path.name} ok")'))

    # ASSERT, do not merely print. A notebook that prints "0 rows" still reports
    # Completed, so the job status would say success while the gold layer was empty.
    # Asserting the exact counts the offline suite verified makes the run status mean
    # something: Completed == the same tables, the same sizes, as test_seeds.py checked.
    expected = {
        "dim_Date": 7670, "dim_Trade": 29, "dim_Status": 32, "dim_Owner": 10,
        "dim_ActivityCategory": 28, "dim_ScorecardWeight": 9, "dim_ScorecardBand": 27,
    }
    cells.append(
        cell(
            f"""
expected = {expected!r}

actual, bad = {{}}, []
for t, want in expected.items():
    got = spark.sql(f"SELECT COUNT(*) AS n FROM {{t}}").collect()[0]["n"]
    actual[t] = got
    flag = "" if got == want else f"   <-- EXPECTED {{want}}"
    print(f"  {{t:<24}} {{got:>6}} rows{{flag}}")
    if got != want:
        bad.append(f"{{t}}: got {{got}}, expected {{want}}")

# The scorecard weights must sum to 1.00 or every project health score is silently wrong.
total = spark.sql(
    "SELECT ROUND(SUM(Weight), 6) AS w FROM dim_ScorecardWeight WHERE EffectiveTo IS NULL"
).collect()[0]["w"]
print(f"\\n  scorecard weights sum to {{total}}")
if float(total) != 1.0:
    bad.append(f"scorecard weights sum to {{total}}, not 1.00")

# Persist the outcome before raising. The Fabric jobs API reports only "statement
# execution failures" with no detail, so without this a failed check is indistinguishable
# from a failed statement - and both just say the run failed.
import json as _json, os as _os
_os.makedirs("/lakehouse/default/Files/_diag", exist_ok=True)
with open("/lakehouse/default/Files/_diag/seed_run.json", "w", encoding="utf-8") as _fh:
    _json.dump({{"counts": actual, "expected": expected, "findings": bad}}, _fh, indent=1)

if bad:
    raise AssertionError("gold seed verification failed:\\n  " + "\\n  ".join(bad))
print("\\nall gold seeds verified in Fabric")
"""
        )
    )
    return notebook(cells)


def payload(nb: dict) -> str:
    return base64.b64encode(json.dumps(nb).encode()).decode()


def attach(nb: dict, lh: dict, workspace_id: str) -> dict:
    """Bind the notebook to CD_Gold_Lakehouse so unqualified table names resolve there."""
    nb["metadata"]["dependencies"] = {
        "lakehouse": {
            "default_lakehouse": lh["id"],
            "default_lakehouse_name": "CD_Gold_Lakehouse",
            "default_lakehouse_workspace_id": workspace_id,
        }
    }
    return nb


def find_item(tok: str, name: str, kind: str) -> dict | None:
    for item in dp.list_items(tok):
        if item["displayName"] == name and item["type"] == kind:
            return item
    return None


def run_notebook(tok: str, item_id: str, timeout: int = 900) -> str:
    """Start the notebook and poll to completion. Returns the terminal status."""
    status, _, headers = dp.call(
        "POST",
        f"/workspaces/{dp.WORKSPACE_ID}/items/{item_id}/jobs/instances?jobType=RunNotebook",
        tok, {},
    )
    location = headers.get("Location", "")
    if not location:
        raise dp.FabricError(f"no job Location header (status {status})")

    deadline = time.time() + timeout
    last = ""
    while time.time() < deadline:
        _, body, _ = dp.call("GET", location, tok)
        last = body.get("status", "")
        if last in ("Completed", "Failed", "Cancelled", "Deduped"):
            if last == "Failed":
                raise dp.FabricError(f"notebook run failed: {body.get('failureReason')}")
            return last
        time.sleep(10)
    raise dp.FabricError(f"notebook did not finish within {timeout}s (last status {last})")


def gold_tables(tok: str, lh: dict) -> list[str]:
    try:
        _, body, _ = dp.call(
            "GET", f"/workspaces/{dp.WORKSPACE_ID}/lakehouses/{lh['id']}/tables", tok
        )
        return sorted(t["name"] for t in body.get("data", []))
    except dp.FabricError as exc:
        # Schema-enabled lakehouses reject the list-tables API - foundation/README.md:78-81.
        # Not a failure, just a different question to ask.
        print(f"  (list-tables unavailable: {str(exc)[:80]})")
        return []


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()

    tok = dp.token()
    lh = lakehouse()
    print(f"gold lakehouse {lh['id']} (schema={lh['defaultSchema']})")

    if args.verify:
        tables = gold_tables(tok, lh)
        print(f"\n{len(tables)} table(s) in CD_Gold_Lakehouse:")
        for name in tables:
            print(f"  {name}")
        return 0

    nb = attach(build_notebook(), lh, dp.WORKSPACE_ID)
    print(f"built {NOTEBOOK_NAME}: {len(nb['cells'])} cells, {len(seed_files())} seed files")

    existing = find_item(tok, NOTEBOOK_NAME, "Notebook")
    action = "update" if existing else "create"
    print(f"would {action} notebook and run it")

    if not args.apply:
        print("\nDRY RUN - nothing written. Re-run with --apply.")
        return 0

    definition = {
        "format": "ipynb",
        "parts": [{"path": "notebook-content.ipynb", "payload": payload(nb),
                   "payloadType": "InlineBase64"}],
    }

    if existing:
        item_id = existing["id"]
        status, _, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items/{item_id}/updateDefinition",
            tok, {"definition": definition},
        )
        if status == 202:
            dp.wait_for_operation(headers, tok)
        print(f"  updated {NOTEBOOK_NAME}")
    else:
        status, body, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items", tok,
            {"displayName": NOTEBOOK_NAME, "type": "Notebook",
             "folderId": dp.FOLDER_ID, "definition": definition},
        )
        if status == 202:
            dp.wait_for_operation(headers, tok)
        item = find_item(tok, NOTEBOOK_NAME, "Notebook")
        item_id = item["id"]
        print(f"  created {NOTEBOOK_NAME} ({item_id})")

    print("  running ...", end=" ", flush=True)
    print(run_notebook(tok, item_id))

    tables = gold_tables(tok, lh)
    if tables:
        print(f"\n{len(tables)} table(s) now in CD_Gold_Lakehouse:")
        for name in tables:
            print(f"  {name}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except dp.FabricError as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
