"""Build, deploy and run the bronze -> silver transforms.

    python deploy_silver.py            # dry run
    python deploy_silver.py --apply    # create/update the notebook and run it

Writes cd_silver_* into CD_Silver_Lakehouse from the raw payloads in CD_Bronze.

Bronze is EMPTY until cd_01_extract_procore can authenticate, so this currently produces
empty silver tables. That is deliberate and useful: the pipeline shape is complete and
provably correct, and the moment credentials land the same notebook fills it. The SQL is
verified offline by _local/tests/test_silver.py (10 assertions) against real payload
shapes.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import deploy as dp  # noqa: E402
import deploy_seeds as ds  # noqa: E402
from make_notebooks import cell, notebook  # noqa: E402

HERE = Path(__file__).resolve().parent
CHARLEY_DEV = HERE.parent
SILVER_DIR = CHARLEY_DEV / "02-transformation" / "sql" / "silver"
# Every silver transform, in filename order. Prefixes carry meaning (naming-standards.md):
# 10_ is the Procore core, 20_ field operations. 00_/01_ are the gold SOURCE views and
# belong to deploy_gold, not here - globbing the whole folder would pull them in and fail
# on placeholders this notebook never substitutes.
#
# 30_manual_silver.sql is DELIBERATELY EXCLUDED. It reads cd_bronze_man_*, which comes from
# ten SharePoint lists that live in Affect's tenant and need SharePoint admin rights to
# create (_docs/sharepoint-lists.md). Including it fails all eleven statements with
# TABLE_OR_VIEW_NOT_FOUND, which would bury a real failure in expected noise.
#
# The empty-stub trick used for the Procore tables does not work here: the manual parsers
# read STRUCT columns (ProjectKey.Title, Editor.Title), and a stub of NULL scalars cannot
# satisfy them. Add "30" below the day the lists exist.
SILVER_FILES = sorted(p for p in SILVER_DIR.glob("*.sql") if p.name[:2] in ("10", "20"))

NOTEBOOK_NAME = "cd_10_bronze_to_silver"

# The bronze contract, exactly as procore_extract.to_bronze_row writes it. Declared here so
# silver builds before ingestion has ever run - otherwise every statement fails with
# "table not found", which looks like broken SQL rather than an empty pipeline.
BRONZE_TABLES = [
    "cd_bronze_procore_projects", "cd_bronze_procore_vendors",
    "cd_bronze_procore_cost_codes", "cd_bronze_procore_prime_contracts",
    "cd_bronze_procore_prime_change_orders", "cd_bronze_procore_budget_detail_rows",
    "cd_bronze_procore_submittals", "cd_bronze_procore_rfis",
    # Field operations - the quality and safety halves of the scorecard.
    "cd_bronze_procore_observations", "cd_bronze_procore_punch_items",
    "cd_bronze_procore_incidents", "cd_bronze_procore_manpower_daily_totals",
]
BRONZE_SCHEMA = ("_key STRING, _project_id STRING, payload STRING, "
                 "_ingested_at TIMESTAMP, _batch_id STRING, _row_hash STRING")


def statements(sql: str) -> list[str]:
    body = "\n".join(line.split("--", 1)[0] for line in sql.splitlines())
    return [s.strip() for s in body.split(";") if s.strip()]


def silver_lakehouse() -> dict:
    ids = json.loads((HERE / "fabric_ids.json").read_text())
    lh = ids["CD_Silver_Lakehouse"]
    assert lh["defaultSchema"] == "dbo", "silver lakehouse is not schema-enabled"
    return lh


def build_notebook() -> dict:
    bronze_id = json.loads((HERE / "fabric_ids.json").read_text())["CD_Bronze_Lakehouse"]["id"]
    bronze_abfss = (f"abfss://{dp.WORKSPACE_ID}@onelake.dfs.fabric.microsoft.com/"
                    f"{bronze_id}/Tables/dbo")

    cells = [
        cell(
            f"""
# {NOTEBOOK_NAME}

Parses the raw Procore payloads in **CD_Bronze_Lakehouse** into typed, trimmed, validated
tables in **CD_Silver_Lakehouse**.

Generated by `_local/deploy_silver.py` - edit the `.sql`, not this notebook.

The column names silver produces are a CONTRACT: they must match what
`sql/silver/01_source_views_cd.sql` exposes as `sv_*`, because every gold file reads
`sv_*` and nothing else. That is what makes switching gold's source a one-file change.

Verified offline by `_local/tests/test_silver.py` - 10 assertions against real payload
shapes, including the sv_* column contract itself.
""",
            "markdown",
        ),
        cell(
            f'''
import json, os, traceback

DIAG = "/lakehouse/default/Files/_diag"
os.makedirs(DIAG, exist_ok=True)
results = []

def run_sql(label, sql):
    try:
        spark.sql(sql)
        results.append({{"step": label, "ok": True}})
    except Exception as exc:
        results.append({{"step": label, "ok": False,
                         "error": f"{{type(exc).__name__}}: {{exc}}"[:1500], "sql": sql[:500]}})
        print(f"  FAILED {{label}}: {{type(exc).__name__}}: {{str(exc)[:300]}}")

# Bronze lives in a DIFFERENT lakehouse, so it is registered as views rather than read
# through the default catalog. CREATE IF NOT EXISTS declares the contract so silver builds
# cleanly before ingestion has ever run - an empty table is a valid state, a missing one
# looks like broken SQL.
# json_field(payload, 'KEY') - look a JSON key up by NAME, not by path.
#
# get_json_object uses a simplified JSONPath that silently returns NULL for bracket keys
# containing '(', ')' or '='. Affect's budget view names its columns
# "UPDATED PRIME CONTRACT BUDGET (D = A+B+C)", so every money column parsed to NULL and
# cd_silver_budgets came out empty - which reads as "Procore has no budget data" rather
# than "the path syntax lost". A dict lookup has no grammar to trip over.
#
# ponytail: a Python UDF, so one interpreter call per row. It is used on ONE table
# (404 budget rows), where that is unmeasurable next to the dialect risk it removes.
# Reach for from_json(payload,'map<string,string>')['KEY'] if it ever spreads to a
# million-row table.
def _json_field(payload, key):
    if not payload:
        return None
    try:
        value = json.loads(payload).get(key)
    except Exception:
        return None
    return None if value is None else str(value)

spark.udf.register("json_field", _json_field, "string")

BRONZE = "{bronze_abfss}"
for t in {BRONZE_TABLES!r}:
    try:
        spark.sql(f"CREATE OR REPLACE TEMPORARY VIEW {{t}} AS "
                  f"SELECT * FROM delta.`{{BRONZE}}/{{t}}`")
    except Exception:
        # Not yet extracted. Declare the shape so the transforms are exercisable now.
        spark.sql(f"CREATE OR REPLACE TEMPORARY VIEW {{t}} AS "
                  f"SELECT * FROM (SELECT NULL AS _key, NULL AS _project_id, "
                  f"NULL AS payload, NULL AS _ingested_at, NULL AS _batch_id, "
                  f"NULL AS _row_hash) WHERE 1=0")
        print(f"  {{t}}: not extracted yet, declared empty")
'''
        ),
    ]

    # One cell per .sql file, labelled with its filename. Labels matter: the run diag
    # records the failing step, and 'silver:7' says far less than
    # '20_fieldops_silver.sql:2' when a statement fails at 6am.
    for path in SILVER_FILES:
        body = "\n".join(
            f"run_sql({json.dumps(path.name + ':' + str(i))}, {json.dumps(s)})\n"
            for i, s in enumerate(statements(path.read_text(encoding="utf-8")))
        )
        cells.append(cell(f"# --- {path.name} ---\n{body}"))

    cells.append(
        cell(
            """
tables = ["cd_silver_projects", "cd_silver_vendors", "cd_silver_cost_codes",
          "cd_silver_prime_contracts", "cd_silver_prime_change_orders",
          "cd_silver_budgets", "cd_silver_submittals", "cd_silver_rfis",
          "cd_silver_observations", "cd_silver_punch_items",
          "cd_silver_incidents", "cd_silver_manpower_daily"]

counts = {}
for t in tables:
    counts[t] = spark.sql(f"SELECT COUNT(*) AS n FROM {t}").collect()[0]["n"]
    print(f"  {t:<34} {counts[t]:>7} rows")

rejects = spark.sql("SELECT COUNT(*) AS n FROM cd_dq_rejects").collect()[0]["n"]
print(f"\\n  cd_dq_rejects {rejects} row(s) - rows that failed their key check")

results.append({"step": "verification", "ok": True, "counts": counts, "rejects": rejects})
with open(f"{DIAG}/silver_run.json", "w", encoding="utf-8") as fh:
    json.dump(results, fh, indent=1)

failed = [r for r in results if not r["ok"]]
if failed:
    raise AssertionError(
        f"{len(failed)} statement(s) failed:\\n  "
        + "\\n  ".join(f"{r['step']}: {r['error'][:200]}" for r in failed[:5]))

# Zero rows is EXPECTED until cd_01_extract_procore can authenticate, so this is not an
# error - but it must be visible, not mistaken for a working pipeline.
if sum(counts.values()) == 0:
    print("\\nAll silver tables are empty - bronze has not been extracted yet.")
    print("See _docs/procore-ingestion.md: the ingestion needs Procore credentials.")
else:
    print(f"\\nsilver built: {sum(counts.values())} rows across {len(tables)} tables")
"""
        )
    )
    return notebook(cells)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    tok = dp.token()
    lh = silver_lakehouse()
    print(f"silver lakehouse {lh['id']}")
    for path in SILVER_FILES:
        print(f"  {path.name:<28} {len(statements(path.read_text(encoding='utf-8')))} statement(s)")

    nb = ds.attach(build_notebook(), lh, dp.WORKSPACE_ID)
    nb["metadata"]["dependencies"]["lakehouse"]["default_lakehouse_name"] = "CD_Silver_Lakehouse"

    existing = ds.find_item(tok, NOTEBOOK_NAME, "Notebook")
    print(f"would {'update' if existing else 'create'} {NOTEBOOK_NAME} "
          f"({len(nb['cells'])} cells) and run it")

    if not args.apply:
        print("\nDRY RUN - nothing written. Re-run with --apply.")
        return 0

    definition = {"format": "ipynb", "parts": [
        {"path": "notebook-content.ipynb", "payload": ds.payload(nb),
         "payloadType": "InlineBase64"}]}

    if existing:
        status, _, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items/{existing['id']}/updateDefinition",
            tok, {"definition": definition})
        if status == 202:
            dp.wait_for_operation(headers, tok)
        item_id = existing["id"]
        print(f"  updated {NOTEBOOK_NAME}")
    else:
        status, _, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items", tok,
            {"displayName": NOTEBOOK_NAME, "type": "Notebook",
             "folderId": dp.FOLDER_ID, "definition": definition})
        if status == 202:
            dp.wait_for_operation(headers, tok)
        item_id = ds.find_item(tok, NOTEBOOK_NAME, "Notebook")["id"]
        print(f"  created {NOTEBOOK_NAME} ({item_id})")

    print("  running ...", end=" ", flush=True)
    print(ds.run_notebook(tok, item_id))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except dp.FabricError as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
