"""Build, deploy and run the gold dimensions and facts in Fabric, against real data.

    python deploy_gold.py            # dry run
    python deploy_gold.py --apply    # create/update the notebook and run it

The generated notebook:
  1. creates the `sv_*` source views over the EXISTING Silver_Lakehouse (READ-ONLY)
  2. runs every sql/gold/1*, 2*, 3* file in order
  3. asserts the result, so a Completed run means the numbers are right

Reading Rebecca's Silver lakehouse is what lets the gold layer be validated against real
data now, rather than waiting for Procore credentials. It is a read: Spark opens the Delta
files, and everything written goes to CD_Gold_Lakehouse. When our own ingestion has
populated CD_Silver, only sql/silver/00_source_views.sql changes - no gold file moves.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import deploy as dp  # noqa: E402
import deploy_seeds as ds  # noqa: E402
from make_notebooks import cell, notebook  # noqa: E402

HERE = Path(__file__).resolve().parent
CHARLEY_DEV = HERE.parent
GOLD_SQL = CHARLEY_DEV / "02-transformation" / "sql" / "gold"
SOURCE_VIEWS = CHARLEY_DEV / "02-transformation" / "sql" / "silver" / "00_source_views.sql"

NOTEBOOK_NAME = "cd_30_build_gold"

# The lakehouse we READ. Rebecca's, untouched - Spark only opens its Delta files.
SILVER_SOURCE_ID = "2e05dca7-ff80-4646-b711-6681dd4993e1"
SILVER_ABFSS = (
    f"abfss://{dp.WORKSPACE_ID}@onelake.dfs.fabric.microsoft.com/{SILVER_SOURCE_ID}/Tables/dbo"
)

# Dimensions, facts and the manual tables. The 0* seed files are built by cd_20_seed_gold.
GOLD_PREFIXES = ("1", "2", "3", "4")


def statements(sql: str) -> list[str]:
    body = "\n".join(line.split("--", 1)[0] for line in sql.splitlines())
    return [s.strip() for s in body.split(";") if s.strip()]


def gold_files() -> list[Path]:
    return sorted(p for p in GOLD_SQL.glob("*.sql") if p.name[0] in GOLD_PREFIXES)


def build_notebook() -> dict:
    cells = [
        cell(
            f"""
# {NOTEBOOK_NAME}

Builds the gold dimensions and facts in **CD_Gold_Lakehouse**.

Generated by `_local/deploy_gold.py` - edit the `.sql`, not this notebook.

Source is the existing **Silver_Lakehouse, read-only** (`{SILVER_SOURCE_ID}`), so the
model can be validated against real data before Procore credentials land. Everything
written goes to CD_Gold_Lakehouse.

The same SQL is verified offline by `_local/tests/test_gold.py` (29 assertions, including
two values from the reconciliation gate) before it ever reaches Fabric.
""",
            "markdown",
        ),
        cell(
            f'''
# --- source views over the existing Silver lakehouse (READ ONLY) ---
SILVER = "{SILVER_ABFSS}"

# The submittals table holds dates before 1582-10-15 - placeholders for "unknown", written
# by an older Spark. Spark 3 refuses to read those from Parquet at all rather than risk a
# silently different value:
#   [INCONSISTENT_BEHAVIOR_CROSS_VERSION.READ_ANCIENT_DATETIME]
# CORRECTED reads them with the modern (Proleptic Gregorian) calendar, which is right for a
# placeholder that was never a real date. sql/silver/00_source_views.sql then floors them
# to NULL so they cannot reach a report.
spark.conf.set("spark.sql.parquet.datetimeRebaseModeInRead", "CORRECTED")
spark.conf.set("spark.sql.parquet.int96RebaseModeInRead", "CORRECTED")
'''
        ),
    ]

    # Every statement runs through run_sql(), which records the failure and keeps going.
    #
    # The Fabric jobs API reports only "statement execution failures" with no cell detail,
    # so a raw exception tells you the run failed and nothing about why. Collecting errors
    # and writing them to Files/ - which is downloadable over the OneLake DFS API - turns a
    # blind failure into a readable report. Without this, diagnosing means bisecting the
    # notebook at roughly two minutes per run.
    cells.append(
        cell(
            """
import json, traceback

DIAG = "/lakehouse/default/Files/_diag"
results = []

def run_sql(label, sql):
    try:
        spark.sql(sql)
        results.append({"step": label, "ok": True})
    except Exception as exc:
        results.append({"step": label, "ok": False,
                        "error": f"{type(exc).__name__}: {exc}"[:2000],
                        "sql": sql[:600]})
        print(f"  FAILED {label}: {type(exc).__name__}: {str(exc)[:300]}")

def write_diag():
    import os
    os.makedirs(DIAG, exist_ok=True)
    with open(f"{DIAG}/gold_run.json", "w", encoding="utf-8") as fh:
        json.dump(results, fh, indent=1)
    print(f"diagnostics written: {len(results)} steps, "
          f"{sum(1 for r in results if not r['ok'])} failed")
"""
        )
    )

    view_sql = SOURCE_VIEWS.read_text(encoding="utf-8").replace("{SILVER_ABFSS}", SILVER_ABFSS)
    body = "\n".join(
        f"run_sql({json.dumps('view:' + str(i))}, {json.dumps(s)})\n"
        for i, s in enumerate(statements(view_sql))
    )
    cells.append(cell(f'{body}\nprint("source views done")'))

    for path in gold_files():
        stmts = statements(path.read_text(encoding="utf-8"))
        body = "\n".join(
            f"run_sql({json.dumps(path.name)}, {json.dumps(s)})\n" for s in stmts
        )
        cells.append(cell(f'# --- {path.name} ---\n{body}'))

    # Load whatever manual data exists. Affect has not decided where the ~40% manual data
    # will live, so this is deliberately the lowest-friction mechanism that works TODAY:
    # drop a CSV in Files/manual/, get a row in the model. It can be replaced by a
    # SharePoint sync without touching a single gold file or measure.
    cells.append(
        cell(
            """
# --- manual input: Files/manual/<table>.csv -> man_<table> ---
import os

MANUAL_DIR = "/lakehouse/default/Files/manual"
manual_tables = ["man_Wins", "man_Risks", "man_PriorityItems", "man_Flags", "man_Survey",
                 "man_SafetyMonthly", "man_QualityMonthly", "man_Milestones",
                 "man_DailyLogCompliance"]

os.makedirs(MANUAL_DIR, exist_ok=True)
loaded = {}
for t in manual_tables:
    schema = spark.table(t).schema          # declared by 40_man_tables.sql
    path = f"{MANUAL_DIR}/{t}.csv"

    if os.path.exists(path):
        # Read against the table's OWN schema rather than inferring. Inference would type
        # an empty column as string and break the next load.
        df = spark.read.option("header", True).schema(schema).csv(f"Files/manual/{t}.csv")
    else:
        # MATERIALISE AN EMPTY DELTA TABLE. `CREATE TABLE (cols)` registers a schema but
        # writes no data files, and Direct Lake cannot bind to that - the model refresh
        # fails with "source tables either do not exist or access was denied", which reads
        # like a permissions problem and is not one. Writing an empty DataFrame produces a
        # real Delta table with a real log, which Direct Lake reads happily as zero rows.
        df = spark.createDataFrame([], schema)

    df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(t)
    loaded[t] = df.count()

for t, n in loaded.items():
    print(f"  {t:<26} {n:>5} rows" + ("" if n else "   (no CSV yet)"))
print(f"manual rows loaded: {sum(loaded.values())}")
"""
        )
    )

    # Assert, do not merely print. A notebook that builds empty tables still reports
    # Completed, so without this the job status would say success over an empty model.
    cells.append(
        cell(
            """
failed = [r for r in results if not r["ok"]]
if failed:
    write_diag()
    raise AssertionError(
        f"{len(failed)} statement(s) failed - see Files/_diag/gold_run.json:\\n  "
        + "\\n  ".join(f"{r['step']}: {r['error'][:200]}" for r in failed[:5])
    )

tables = ["dim_Project", "dim_Vendor", "dim_CostCode", "fct_BudgetLine",
          "fct_ChangeOrder", "fct_Invoice", "fct_RfiSubmittal", "fct_Milestone",
          "fct_FinancialPeriod"]

counts, bad = {}, []
for t in tables:
    n = spark.sql(f"SELECT COUNT(*) AS n FROM {t}").collect()[0]["n"]
    counts[t] = n
    print(f"  {t:<24} {n:>7} rows")
    if n == 0:
        bad.append(f"{t} is EMPTY")

# Referential integrity: a fact key that does not resolve means the report silently
# drops rows. Checked here rather than discovered in a dashboard.
for fact, col, dim, key in [
    ("fct_BudgetLine", "ProjectKey", "dim_Project", "ProjectKey"),
    ("fct_BudgetLine", "CostCodeKey", "dim_CostCode", "CostCodeKey"),
    ("fct_ChangeOrder", "ProjectKey", "dim_Project", "ProjectKey"),
    ("fct_RfiSubmittal", "ProjectKey", "dim_Project", "ProjectKey"),
    ("fct_Milestone", "ProjectKey", "dim_Project", "ProjectKey"),
]:
    orphans = spark.sql(
        f"SELECT COUNT(*) AS n FROM {fact} f LEFT JOIN {dim} d ON f.{col} = d.{key} "
        f"WHERE f.{col} IS NOT NULL AND d.{key} IS NULL"
    ).collect()[0]["n"]
    if orphans:
        bad.append(f"{fact}.{col}: {orphans} orphan(s) not in {dim}")
    print(f"  {fact}.{col} -> {dim}: {orphans} orphans")

# Every fact month must exist in dim_Date or time intelligence silently returns blank -
# the exact failure dim_Date was built to eliminate.
for fact in ["fct_BudgetLine", "fct_ChangeOrder", "fct_Invoice", "fct_RfiSubmittal",
             "fct_Milestone", "fct_FinancialPeriod"]:
    missing = spark.sql(
        f"SELECT COUNT(*) AS n FROM {fact} f LEFT JOIN dim_Date d ON f.MonthStart = d.Date "
        f"WHERE f.MonthStart IS NOT NULL AND d.Date IS NULL"
    ).collect()[0]["n"]
    if missing:
        bad.append(f"{fact}.MonthStart: {missing} row(s) outside dim_Date")

# Sentinel dates must not survive into gold. The source carries dates before 1582 as
# placeholders for "unknown"; sql/silver/00_source_views.sql floors them to NULL. That
# guard is Spark-only, so this is where it gets verified.
for fact, col in [("fct_RfiSubmittal", "CreatedDate"), ("fct_RfiSubmittal", "DueDate"),
                  ("fct_RfiSubmittal", "RespondedDate"), ("fct_Milestone", "CurrentStart"),
                  ("fct_Milestone", "CurrentFinish")]:
    n = spark.sql(
        f"SELECT COUNT(*) AS n FROM {fact} WHERE {col} < DATE '1990-01-01'"
    ).collect()[0]["n"]
    if n:
        bad.append(f"{fact}.{col}: {n} sentinel date(s) survived the silver floor")
print(f"  sentinel-date guard: checked 5 date columns")

# Record the verification outcome alongside the statement results, so a failed CHECK is
# as diagnosable as a failed statement. Without this the run just says "failed" again.
results.append({"step": "verification", "ok": not bad,
                "counts": counts, "findings": bad})

# Publish the ACTUAL Spark schema. The semantic model's TMDL types must match what Fabric
# really has; inferring them from the offline DuckDB build is unsound, because DuckDB
# reads DECIMAL from a VALUES literal where Spark has DOUBLE. A declared type that does not
# match makes DirectLake drop the whole table - silently, as a missing table.
schema = {}
for t in tables + ["dim_Date", "dim_Trade", "dim_Status", "dim_Owner",
                   "dim_ActivityCategory", "dim_ScorecardWeight", "dim_ScorecardBand",
                   "measures_anchor"] + manual_tables:
    schema[t] = [(f.name, f.dataType.simpleString()) for f in spark.table(t).schema.fields]
with open(f"{DIAG}/gold_schema.json", "w", encoding="utf-8") as fh:
    json.dump(schema, fh, indent=1)
print(f"  published schema for {len(schema)} tables")

write_diag()

if bad:
    raise AssertionError("gold verification failed:\\n  " + "\\n  ".join(bad))
print("\\nall gold tables built and verified in Fabric")
"""
        )
    )
    return notebook(cells)


def fetch_diagnostics(lakehouse_id: str, name: str = "gold_run.json") -> list[dict] | None:
    """Download Files/_diag/gold_run.json from OneLake.

    The Fabric jobs API reports statement failures with no cell detail, so this is the
    only way to see WHICH statement failed and why. OneLake speaks the ADLS Gen2 DFS API
    and takes a storage-scoped token, which is a different audience from the Fabric API.
    """
    import subprocess
    import urllib.error
    import urllib.request

    result = subprocess.run(
        [dp.az_path(), "account", "get-access-token",
         "--resource", "https://storage.azure.com", "--query", "accessToken", "-o", "tsv"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"  (storage token failed: {result.stderr.strip()[:120]})")
        return None

    url = (f"https://onelake.dfs.fabric.microsoft.com/{dp.WORKSPACE_ID}/"
           f"{lakehouse_id}/Files/_diag/{name}")
    request = urllib.request.Request(
        url, headers={"Authorization": f"Bearer {result.stdout.strip()}"}
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            return json.loads(response.read().decode())
    except urllib.error.HTTPError as exc:
        print(f"  (no diagnostics file: {exc.code})")
        return None


def report_diagnostics(lakehouse_id: str) -> None:
    diag = fetch_diagnostics(lakehouse_id)
    if not diag:
        return
    failed = [r for r in diag if not r.get("ok")]
    print(f"\ndiagnostics: {len(diag)} statements, {len(failed)} failed")
    for r in failed:
        print(f"\n  STEP {r['step']}")
        print(f"  {r.get('error', '')[:600]}")
        print(f"  sql: {r.get('sql', '')[:300]}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--diag", action="store_true", help="download the last run's diagnostics")
    args = parser.parse_args()

    if args.diag:
        report_diagnostics(ds.lakehouse()["id"])
        return 0

    tok = dp.token()
    lh = ds.lakehouse()
    files = gold_files()
    print(f"gold lakehouse {lh['id']}")
    print(f"reading source: Silver_Lakehouse {SILVER_SOURCE_ID} (read-only)")
    print(f"{len(files)} gold file(s): {', '.join(p.name for p in files)}")

    nb = ds.attach(build_notebook(), lh, dp.WORKSPACE_ID)
    existing = ds.find_item(tok, NOTEBOOK_NAME, "Notebook")
    print(f"would {'update' if existing else 'create'} {NOTEBOOK_NAME} ({len(nb['cells'])} cells) and run it")

    if not args.apply:
        print("\nDRY RUN - nothing written. Re-run with --apply.")
        return 0

    definition = {
        "format": "ipynb",
        "parts": [{"path": "notebook-content.ipynb", "payload": ds.payload(nb),
                   "payloadType": "InlineBase64"}],
    }

    if existing:
        item_id = existing["id"]
        status, _, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items/{item_id}/updateDefinition",
            tok, {"definition": definition},
        )
        if status == 202:
            dp.wait_for_operation(headers, tok)
        print(f"  updated {NOTEBOOK_NAME}")
    else:
        status, _, headers = dp.call(
            "POST", f"/workspaces/{dp.WORKSPACE_ID}/items", tok,
            {"displayName": NOTEBOOK_NAME, "type": "Notebook",
             "folderId": dp.FOLDER_ID, "definition": definition},
        )
        if status == 202:
            dp.wait_for_operation(headers, tok)
        item_id = ds.find_item(tok, NOTEBOOK_NAME, "Notebook")["id"]
        print(f"  created {NOTEBOOK_NAME} ({item_id})")

    print("  running ...", end=" ", flush=True)
    print(ds.run_notebook(tok, item_id))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except dp.FabricError as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
