"""Generate _docs/endpoint-inventory.md from the registry.

Generated rather than hand-written so it cannot drift from config/endpoints.yml. A
stale endpoint inventory is worse than none - it gets trusted.

Run:  python make_endpoint_inventory.py
"""

from __future__ import annotations

import sys
from pathlib import Path

CHARLEY_DEV = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(CHARLEY_DEV / "00-platform" / "lib"))

import procore_scope as ps  # noqa: E402

REGISTRY = CHARLEY_DEV / "01-ingestion" / "Procore" / "config" / "endpoints.yml"
OUT = CHARLEY_DEV / "_docs" / "endpoint-inventory.md"

# Which endpoints already have an equivalent landing in Rebecca's lakehouses, from
# foundation/03-lakehouses/*.schema.json. "new" means nothing equivalent exists today -
# that is the actual gap this build closes.
EXISTING = {
    "projects": "Bronze.procore_projects_raw (18)",
    "vendors": "Bronze.procore_vendors_raw (1,075)",
    "project_vendors": "Bronze.procore_project_vendors_raw (1,086)",
    "cost_codes": "Bronze.procore_cost_codes_raw (4,765)",
    "prime_contracts": "Bronze.procore_prime_contracts_raw (20)",
    "prime_contract_line_items": "Bronze.procore_prime_contract_line_items (317)",
    "payment_applications": "Bronze.procore_payment_applications_raw (108)",
    "requisitions": "Bronze.procore_requisitions_raw (556)",
    "commitments": "Bronze.procore_commitments_raw (264)",
    "budget": "Bronze.procore_budgets_raw (808)",
    "submittals": "Bronze.procore_submittals_raw (2,242)",
    "potential_change_orders": "Bronze.procore_prime_change_orders (2,270)",
    "work_order_contracts": "Bronze.procore_work_order_line_items (241)",
}

# What each gap endpoint unblocks in the Monthly Progress Report.
FEEDS = {
    "rfis": "fct_RfiSubmittal - the missing half of the workbook's only chart",
    "rfi_statuses": "dim_Status RfiStatus domain",
    "rfi_priorities": "the likely definition of 'critical' (open question #5)",
    "observations": "fct_QualityMonthly - fixes defect #2",
    "punch_items": "fct_QualityMonthly, fct_QualityItem",
    "incidents": "fct_SafetyMonthly[RecordableIncidents]",
    "manpower_daily_totals": "fct_ManpowerDaily - SCHEDULE!Table14, without the 5-sub cap",
    "daily_log_headers": "fct_DailyLog - scorecard 'Daily Reports', typed by hand today",
    "change_order_requests": "[AgeOfOldestUnapprovedCO] - FINANCIALS!C6, typed by hand today",
    "budget_detail_rows": "fct_BudgetLine at cost-code grain",
    "direct_costs": "fct_BudgetLine[SpentToDate]",
    "inspection_logs": "fct_QualityItem",
    "schedule": "comparison only - Procore has no milestone endpoint (Outbuild is the source)",
}


def table(endpoints: list[ps.Endpoint]) -> str:
    rows = [
        "| Endpoint | Path | Scope | Ver | Load | Status today |",
        "|---|---|---|---|---|---|",
    ]
    for e in endpoints:
        load = "incremental" if e.incremental else "full"
        status = EXISTING.get(e.name, "**new**")
        rows.append(
            f"| `{e.name}` | `{e.path}` | {e.scope} | {e.api_version} | {load} | {status} |"
        )
    return "\n".join(rows)


def main() -> int:
    endpoints = ps.load_registry(str(REGISTRY))
    ordered = ps.resolution_order(endpoints)
    new = [e for e in ordered if e.name not in EXISTING]
    incremental = [e for e in ordered if e.incremental]

    body = f"""# Procore endpoint inventory (D1)

**Generated by `_local/make_endpoint_inventory.py` from
`01-ingestion/Procore/config/endpoints.yml`. Do not edit by hand.**

Every path is verified against `resources/procore/endpoints-cheatsheet.md`, with the
verifying line cited inline in the registry. Nothing here is guessed.

The field-by-field map from Excel cell to model column lives in
[`../../../powerbi/source-mapping.md`](../../../powerbi/source-mapping.md). This document
adds what that one could not: which endpoints are **already landing** in the existing
lakehouses, and which are **genuinely missing**.

## Summary

| | Count |
|---|---|
| Endpoints in the registry | **{len(ordered)}** |
| Already landing in Bronze/Silver today | {len(ordered) - len(new)} |
| **New — the actual gap this build closes** | **{len(new)}** |
| Incremental (verified `filters[updated_at]`) | {len(incremental)} |
| Requiring the `Procore-Company-Id` header (v2.0+) | {sum(1 for e in ordered if e.needs_company_header)} |

## The gap — what does not exist today

These are why the Monthly Progress Report cannot be automated from the current
warehouse. Each one is a section of the workbook that is hand-typed.

| Endpoint | Unblocks |
|---|---|
""" + "\n".join(
        f"| `{e.name}` | {FEEDS.get(e.name, '—')} |" for e in new if e.name in FEEDS
    ) + f"""

## Incremental loading

Only {len(incremental)} endpoints declare a watermark filter, and only where the
cheatsheet confirms the endpoint accepts `filters[updated_at]`:

{chr(10).join(f'- `{e.name}`' for e in incremental)}

**RFIs and submittals are deliberately excluded.** Both document `filters[created_at]`
but not `filters[updated_at]`. Incrementing on `created_at` would miss status changes on
existing records — and "open critical RFIs" is precisely a status question. They stay
full reloads until confirmed against a live tenant. Re-running is safe regardless: the
load is a `MERGE` on the natural key, not an append.

## Full registry

{table(ordered)}

## Notes

- **Version mixing is expected.** v1.0, v1.1 and v2.0 appear in one pipeline (RFIs are
  v1.0, submittals v1.1, commitment contracts v2.0). That is how Procore versions its
  API, not a mistake to correct.
- **The company header is version-dependent.** v2.0+ requires `Procore-Company-Id`;
  v1.x takes the company in the path or query. Sending it to the wrong version is the
  most common cause of an unexplained 403, so the rule is implemented once and asserted
  in `_local/tests/test_extractor_compat.py`.
- **Parent-scoped endpoints** (`{', '.join(e.name for e in ordered if e.parent)}`) need
  an id from a prior call. The registry declares the dependency and the runner
  topologically orders it, so a parent is always fetched first.
- **Active projects only.** The existing notebooks loop every project on every run; most
  are closed. Flagged in the Jul 23 warehouse review.
"""

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"  wrote {OUT.relative_to(CHARLEY_DEV)}")
    print(f"  {len(ordered)} endpoints, {len(new)} new, {len(incremental)} incremental")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
