-- gold: seed_ProjectCrosswalk - the Procore project <-> Sage job mapping.
--
-- GENERATED by _local/make_qc_seeds.py from 02-transformation/seed/project_crosswalk.csv.
-- Do not edit by hand. Sage actrec carries no Procore reference, so this cannot be
-- derived; every row is a human decision. The first 15 are the legacy
-- dim_projects_procoreXsage verbatim. gold dq_CrosswalkCandidate proposes new pairs; a
-- proposal becomes a row here only through a reviewed CSV edit, never automatically.

-- seed_ProjectCrosswalk: 15 row(s) from seed/project_crosswalk.csv
CREATE OR REPLACE TABLE seed_ProjectCrosswalk AS
SELECT CAST(c1 AS STRING) AS ProcoreProjectId,
       CAST(c2 AS STRING) AS SageJobNumber,
       CAST(c3 AS STRING) AS Relationship,
       CAST(c4 AS STRING) AS Source
FROM (VALUES
    ('562949954833574', '1', 'primary', 'legacy_verified_2026-09-13'),
    ('562949954507004', '3', 'primary', 'legacy_verified_2026-09-13'),
    ('562949955001573', '5', 'primary', 'legacy_verified_2026-09-13'),
    ('562949954973730', '6', 'primary', 'legacy_verified_2026-09-13'),
    ('562949955064640', '9', 'primary', 'legacy_verified_2026-09-13'),
    ('562949954997327', '10', 'primary', 'legacy_verified_2026-09-13'),
    ('562949954973684', '11', 'primary', 'legacy_verified_2026-09-13'),
    ('562949955118102', '12', 'primary', 'legacy_verified_2026-09-13'),
    ('562949954971827', '15', 'primary', 'legacy_verified_2026-09-13'),
    ('562949955225798', '16', 'primary', 'legacy_verified_2026-09-13'),
    ('562949955257421', '17', 'primary', 'legacy_verified_2026-09-13'),
    ('562949955318524', '18', 'primary', 'legacy_verified_2026-09-13'),
    ('562949955286476', '19', 'primary', 'legacy_verified_2026-09-13'),
    ('562949955375634', '20', 'primary', 'legacy_verified_2026-09-13'),
    ('562949955365267', '22', 'primary', 'legacy_verified_2026-09-13')
) AS t(c1, c2, c3, c4);
