[DefaultOutputDestinationSettings = [DestinationDefinition = [Kind = "Reference", QueryName = "DefaultDestination", IsNewTarget = true], UpdateMethod = [Kind = "Replace"], DestinationTypeSettings = [Kind = "Table"]], StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[BindToDefaultDestination = true]
shared procore_budgets_silver = let
  Source = Sql.Database("lmrkfmsojpwefossy7q4fxvfqa-22xhyh4k7bje5pedtjeyufstae.datawarehouse.fabric.microsoft.com", "Bronze_Lakehouse"),
  Navigation = Source{[Schema = "dbo", Item = "procore_budgets_raw"]}[Data],
  #"Changed column type" = Table.TransformColumnTypes(Navigation, {{"start_date", type date}, {"end_date", type date}, {"unit_cost", Currency.Type}, {"quantity", type number}, {"original_budget_amount", Currency.Type}, {"budget_modifications", Currency.Type}, {"DIRECT_COSTS_J", Currency.Type}, {"COMMITTMENT_CO'S_H", Currency.Type}, {"COMMITTED_COSTS_G", Currency.Type}, {"PENDING_PRIME_CONTRACT_CO_E", Currency.Type}, {"APPROVED_PRIME_CONTRACT_CO_C", Currency.Type}, {"PENDING_CO'S_M", Currency.Type}, {"BALANCE_TO_FINISH_R_D-P", Currency.Type}, {"COST_TO_COMPLETE_Q_K-P", Currency.Type}, {"INVOICED_TO_DATE_P", Currency.Type}, {"PROJECTED_OVER/UNDER_O_F-N", Currency.Type}, {"OVER/UNDER_L_D-K", Currency.Type}, {"TOTAL_COMMITTED_TO_DATE_K_G+H+I+J", Currency.Type}, {"PROJECTED_PRIME_CONTRACT_BUDGET_F_D+E", Currency.Type}, {"UPDATED_PRIME_CONTRACT_BUDGET_D_A+B+C", Currency.Type}, {"PROJECTED_COMMITTED_BUDGET_N_K+M", Currency.Type}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Changed column type", {{"%_OVER/UNDER", type number}}),
  #"Reordered columns" = Table.ReorderColumns(#"Changed column type 1", {"curve", "start_date", "end_date", "deletable", "budgeted", "budgetable", "budget_forecast", "wbs_code", "wbs_code_id", "currency_configuration", "id", "budget_row_id", "biller_id", "root_cost_code_id", "cost_code_id", "cost_code_level_1_id", "cost_code_level_2_id", "cost_code_level_3_id", "cost_code_level_4_id", "cost_code_level_5_id", "cost_code_level_1", "cost_code_level_2", "category_id", "biller", "biller_type", "root_cost_code", "cost_code", "category", "uom", "unit_cost", "quantity", "calculation_strategy", "project_id", "project", "company_id", "company", "original_budget_amount", "budget_modifications", "DIRECT_COSTS_J", "COMMITTMENT_CO'S_H", "COMMITTED_COSTS_G", "PENDING_PRIME_CONTRACT_CO_E", "APPROVED_PRIME_CONTRACT_CO_C", "PENDING_CO'S_M", "BALANCE_TO_FINISH_R_D-P", "COST_TO_COMPLETE_Q_K-P", "INVOICED_TO_DATE_P", "PROJECTED_OVER/UNDER_O_F-N", "OVER/UNDER_L_D-K", "TOTAL_COMMITTED_TO_DATE_K_G+H+I+J", "PROJECTED_PRIME_CONTRACT_BUDGET_F_D+E", "UPDATED_PRIME_CONTRACT_BUDGET_D_A+B+C", "PROJECTED_COMMITTED_BUDGET_N_K+M", "%_OVER/UNDER", "project_name", "snapshot_date"}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Reordered columns", {{"snapshot_date", type date}}),
  #"Renamed columns" = Table.RenameColumns(#"Changed column type 2", {{"project_id", "Project ID"}}),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Renamed columns", {{"Project ID", type text}}),
  #"Reordered columns 1" = Table.ReorderColumns(#"Changed column type 3", {"Project ID", "curve", "start_date", "end_date", "deletable", "budgeted", "budgetable", "budget_forecast", "wbs_code", "wbs_code_id", "currency_configuration", "id", "budget_row_id", "biller_id", "root_cost_code_id", "cost_code_id", "cost_code_level_1_id", "cost_code_level_2_id", "cost_code_level_3_id", "cost_code_level_4_id", "cost_code_level_5_id", "cost_code_level_1", "cost_code_level_2", "category_id", "biller", "biller_type", "root_cost_code", "cost_code", "category", "uom", "unit_cost", "quantity", "calculation_strategy", "project", "company_id", "company", "original_budget_amount", "budget_modifications", "DIRECT_COSTS_J", "COMMITTMENT_CO'S_H", "COMMITTED_COSTS_G", "PENDING_PRIME_CONTRACT_CO_E", "APPROVED_PRIME_CONTRACT_CO_C", "PENDING_CO'S_M", "BALANCE_TO_FINISH_R_D-P", "COST_TO_COMPLETE_Q_K-P", "INVOICED_TO_DATE_P", "PROJECTED_OVER/UNDER_O_F-N", "OVER/UNDER_L_D-K", "TOTAL_COMMITTED_TO_DATE_K_G+H+I+J", "PROJECTED_PRIME_CONTRACT_BUDGET_F_D+E", "UPDATED_PRIME_CONTRACT_BUDGET_D_A+B+C", "PROJECTED_COMMITTED_BUDGET_N_K+M", "%_OVER/UNDER", "cost_code_origin_id", "project_name", "snapshot_date"}),
  #"Renamed columns 1" = Table.RenameColumns(#"Reordered columns 1", {{"cost_code_id", "Cost Code ID"}}),
  #"Changed column type 4" = Table.TransformColumnTypes(#"Renamed columns 1", {{"Cost Code ID", type text}}),
  #"Reordered columns 2" = Table.ReorderColumns(#"Changed column type 4", {"Cost Code ID", "Project ID", "curve", "start_date", "end_date", "deletable", "budgeted", "budgetable", "budget_forecast", "wbs_code", "wbs_code_id", "currency_configuration", "id", "budget_row_id", "biller_id", "root_cost_code_id", "cost_code_level_1_id", "cost_code_level_2_id", "cost_code_level_3_id", "cost_code_level_4_id", "cost_code_level_5_id", "cost_code_level_1", "cost_code_level_2", "category_id", "biller", "biller_type", "root_cost_code", "cost_code", "category", "uom", "unit_cost", "quantity", "calculation_strategy", "project", "company_id", "company", "original_budget_amount", "budget_modifications", "DIRECT_COSTS_J", "COMMITTMENT_CO'S_H", "COMMITTED_COSTS_G", "PENDING_PRIME_CONTRACT_CO_E", "APPROVED_PRIME_CONTRACT_CO_C", "PENDING_CO'S_M", "BALANCE_TO_FINISH_R_D-P", "COST_TO_COMPLETE_Q_K-P", "INVOICED_TO_DATE_P", "PROJECTED_OVER/UNDER_O_F-N", "OVER/UNDER_L_D-K", "TOTAL_COMMITTED_TO_DATE_K_G+H+I+J", "PROJECTED_PRIME_CONTRACT_BUDGET_F_D+E", "UPDATED_PRIME_CONTRACT_BUDGET_D_A+B+C", "PROJECTED_COMMITTED_BUDGET_N_K+M", "%_OVER/UNDER", "cost_code_origin_id", "project_name", "snapshot_date"}),
  #"Removed columns" = Table.RemoveColumns(#"Reordered columns 2", {"company", "company_id"}),
  #"Divided column" = Table.TransformColumns(#"Removed columns", {{"%_OVER/UNDER", each _ / 100, type number}}),
  #"Changed column type 5" = Table.TransformColumnTypes(#"Divided column", {{"%_OVER/UNDER", Percentage.Type}}),
  #"Removed columns 1" = Table.RemoveColumns(#"Changed column type 5", {"budget_forecast", "currency_configuration"}),
  #"Reordered columns 3" = Table.ReorderColumns(#"Removed columns 1", {"Cost Code ID", "Project ID", "curve", "start_date", "end_date", "deletable", "budgeted", "id", "wbs_code_id", "budgetable", "wbs_code", "budget_row_id", "biller_id", "root_cost_code_id", "cost_code_level_1_id", "cost_code_level_2_id", "cost_code_level_3_id", "cost_code_level_4_id", "cost_code_level_5_id", "cost_code_level_1", "cost_code_level_2", "category_id", "biller", "biller_type", "root_cost_code", "cost_code", "category", "uom", "unit_cost", "quantity", "calculation_strategy", "project", "original_budget_amount", "budget_modifications", "DIRECT_COSTS_J", "COMMITTMENT_CO'S_H", "COMMITTED_COSTS_G", "PENDING_PRIME_CONTRACT_CO_E", "APPROVED_PRIME_CONTRACT_CO_C", "PENDING_CO'S_M", "BALANCE_TO_FINISH_R_D-P", "COST_TO_COMPLETE_Q_K-P", "INVOICED_TO_DATE_P", "PROJECTED_OVER/UNDER_O_F-N", "OVER/UNDER_L_D-K", "TOTAL_COMMITTED_TO_DATE_K_G+H+I+J", "PROJECTED_PRIME_CONTRACT_BUDGET_F_D+E", "UPDATED_PRIME_CONTRACT_BUDGET_D_A+B+C", "PROJECTED_COMMITTED_BUDGET_N_K+M", "%_OVER/UNDER", "cost_code_origin_id", "project_name", "snapshot_date"}),
  #"Removed columns 2" = Table.RemoveColumns(#"Reordered columns 3", {"budget_row_id", "cost_code_level_5_id", "cost_code_level_4_id", "cost_code_level_3_id", "cost_code_level_1", "cost_code_level_2", "biller", "biller_type", "project_name"}),
  #"Renamed columns 2" = Table.RenameColumns(#"Removed columns 2", {{"uom", "Unit Of Measurment"}}),
  #"Removed columns 3" = Table.RemoveColumns(#"Renamed columns 2", {"biller_id", "wbs_code"})
in
  #"Removed columns 3";
shared DefaultDestination = Lakehouse.Contents([EnableFolding = false]){[workspaceId = "1f7caed6-f88a-4e52-bc83-9a498a165301"]}[Data]{[lakehouseId = "2e05dca7-ff80-4646-b711-6681dd4993e1"]}[Data];
[BindToDefaultDestination = true]
shared procore_budgets_costcodes_level2 = let
  Source = procore_budgets_silver,
  #"Removed other columns" = Table.SelectColumns(Source, {"cost_code", "root_cost_code", "category_id", "cost_code_level_2_id", "cost_code_level_1_id", "root_cost_code_id", "Cost Code ID"}),
  #"Reordered columns" = Table.ReorderColumns(#"Removed other columns", {"root_cost_code", "cost_code", "category_id", "cost_code_level_2_id", "cost_code_level_1_id", "Cost Code ID", "root_cost_code_id"}),
  #"Renamed columns" = Table.RenameColumns(#"Reordered columns", {{"cost_code_level_1_id", "Root Cost Code ID"}})
in
  #"Renamed columns";
