[DefaultOutputDestinationSettings = [DestinationDefinition = [Kind = "Reference", QueryName = "DefaultDestination", IsNewTarget = true], UpdateMethod = [Kind = "Replace"], DestinationTypeSettings = [Kind = "Table"]], StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[BindToDefaultDestination = true]
shared procore_payment_applications_silver = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "1f7caed6-f88a-4e52-bc83-9a498a165301"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "4256b1ed-3884-4e26-96b5-aac4d8e6281f"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "procore_payment_applications_raw", ItemKind = "Table"]}[Data],
  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 2", {{"billing_date", type date}, {"period_start", type date}, {"period_end", type date}, {"total_amount_paid", Currency.Type}, {"total_amount_accrued_this_period", Currency.Type}}),
  #"Parsed JSON" = Table.TransformColumns(#"Changed column type", {{"g702", each Json.Document(_), type any}}),
  #"Expanded g702" = Table.ExpandRecordColumn(#"Parsed JSON", "g702", {"balance_to_finish_including_retainage", "completed_work_retainage_amount", "completed_work_retainage_percent", "contract_sum_to_date", "current_payment_due", "formatted_period", "less_previous_certificates_for_payment", "negative_change_order_item_total", "negative_new_change_order_item_total", "negative_previous_change_order_item_total", "net_change_by_change_orders", "original_contract_sum", "positive_change_order_item_total", "positive_new_change_order_item_total", "positive_previous_change_order_item_total", "stored_materials_retainage_amount", "stored_materials_retainage_percent", "tax_applicable_to_this_payment", "total_completed_and_stored_to_date", "total_earned_less_retainage", "total_retainage"}, {"balance_to_finish_including_retainage", "completed_work_retainage_amount", "completed_work_retainage_percent", "contract_sum_to_date", "current_payment_due", "formatted_period", "less_previous_certificates_for_payment", "negative_change_order_item_total", "negative_new_change_order_item_total", "negative_previous_change_order_item_total", "net_change_by_change_orders", "original_contract_sum", "positive_change_order_item_total", "positive_new_change_order_item_total", "positive_previous_change_order_item_total", "stored_materials_retainage_amount", "stored_materials_retainage_percent", "tax_applicable_to_this_payment", "total_completed_and_stored_to_date", "total_earned_less_retainage", "total_retainage"}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Expanded g702", {{"balance_to_finish_including_retainage", Currency.Type}, {"completed_work_retainage_amount", Currency.Type}, {"contract_sum_to_date", Currency.Type}, {"current_payment_due", Currency.Type}, {"less_previous_certificates_for_payment", Currency.Type}, {"negative_change_order_item_total", Currency.Type}, {"negative_new_change_order_item_total", Currency.Type}, {"negative_previous_change_order_item_total", Currency.Type}, {"net_change_by_change_orders", Currency.Type}, {"original_contract_sum", Currency.Type}, {"positive_change_order_item_total", Currency.Type}, {"positive_new_change_order_item_total", Currency.Type}, {"positive_previous_change_order_item_total", Currency.Type}, {"stored_materials_retainage_amount", Currency.Type}}),
  #"Removed columns" = Table.RemoveColumns(#"Changed column type 1", {"tax_applicable_to_this_payment"}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Removed columns", {{"total_completed_and_stored_to_date", Currency.Type}, {"total_earned_less_retainage", Currency.Type}, {"total_retainage", Currency.Type}}),
  #"Parsed JSON 1" = Table.TransformColumns(#"Changed column type 2", {{"contract", each Json.Document(_), type any}}),
  #"Expanded contract" = Table.ExpandRecordColumn(#"Parsed JSON 1", "contract", {"id", "title", "type"}, {"id.1", "title", "type"}),
  #"Removed columns 1" = Table.RemoveColumns(#"Expanded contract", {"type", "billing_period", "id.1", "title"}),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Removed columns 1", {{"percent_complete", type number}}),
  #"Added custom" = Table.AddColumn(#"Changed column type 3", "Custom", each [percent_complete] / 100),
  #"Reordered columns" = Table.ReorderColumns(#"Added custom", {"id", "billing_date", "invoice_number", "percent_complete", "Custom", "period_start", "period_end", "period_id", "status", "description_type", "total_amount_paid", "total_amount_accrued_this_period", "formatted_contract_company", "created_at", "updated_at", "currency_configuration", "number", "payment_status", "payment_application_url", "prime_contract_url", "balance_to_finish_including_retainage", "completed_work_retainage_amount", "completed_work_retainage_percent", "contract_sum_to_date", "current_payment_due", "formatted_period", "less_previous_certificates_for_payment", "negative_change_order_item_total", "negative_new_change_order_item_total", "negative_previous_change_order_item_total", "net_change_by_change_orders", "original_contract_sum", "positive_change_order_item_total", "positive_new_change_order_item_total", "positive_previous_change_order_item_total", "stored_materials_retainage_amount", "stored_materials_retainage_percent", "total_completed_and_stored_to_date", "total_earned_less_retainage", "total_retainage", "project_id", "project_name"}),
  #"Removed columns 2" = Table.RemoveColumns(#"Reordered columns", {"percent_complete"}),
  #"Renamed columns" = Table.RenameColumns(#"Removed columns 2", {{"Custom", "percent_complete"}}),
  #"Changed column type 4" = Table.TransformColumnTypes(#"Renamed columns", {{"percent_complete", Percentage.Type}}),
  #"Removed columns 3" = Table.RemoveColumns(#"Changed column type 4", {"description_type", "currency_configuration", "payment_application_url", "prime_contract_url"}),
  #"Changed column type 5" = Table.TransformColumnTypes(#"Removed columns 3", {{"completed_work_retainage_percent", type number}}),
  #"Added custom 1" = Table.AddColumn(#"Changed column type 5", "Custom", each [completed_work_retainage_percent] / 100),
  #"Reordered columns 1" = Table.ReorderColumns(#"Added custom 1", {"id", "billing_date", "invoice_number", "percent_complete", "period_start", "period_end", "period_id", "status", "total_amount_paid", "total_amount_accrued_this_period", "formatted_contract_company", "created_at", "updated_at", "number", "payment_status", "balance_to_finish_including_retainage", "completed_work_retainage_amount", "completed_work_retainage_percent", "Custom", "contract_sum_to_date", "current_payment_due", "formatted_period", "less_previous_certificates_for_payment", "negative_change_order_item_total", "negative_new_change_order_item_total", "negative_previous_change_order_item_total", "net_change_by_change_orders", "original_contract_sum", "positive_change_order_item_total", "positive_new_change_order_item_total", "positive_previous_change_order_item_total", "stored_materials_retainage_amount", "stored_materials_retainage_percent", "total_completed_and_stored_to_date", "total_earned_less_retainage", "total_retainage", "project_id", "project_name"}),
  #"Changed column type 6" = Table.TransformColumnTypes(#"Reordered columns 1", {{"Custom", Percentage.Type}}),
  #"Removed columns 4" = Table.RemoveColumns(#"Changed column type 6", {"completed_work_retainage_percent"}),
  #"Renamed columns 1" = Table.RenameColumns(#"Removed columns 4", {{"Custom", "completed_work_retainage_percent"}}),
  #"Changed column type 7" = Table.TransformColumnTypes(#"Renamed columns 1", {{"period_id", Int64.Type}})
in
  #"Changed column type 7";
shared DefaultDestination = Lakehouse.Contents([EnableFolding = false]){[workspaceId = "1f7caed6-f88a-4e52-bc83-9a498a165301"]}[Data]{[lakehouseId = "2e05dca7-ff80-4646-b711-6681dd4993e1"]}[Data];
